package skyline.repository.model;

public class Ptmenutop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMENUTOP.OPERID
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMENUTOP.MENUID
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMENUTOP.VISIT_TIMES
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    private Integer visitTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMENUTOP.OPERID
     *
     * @return the value of PTMENUTOP.OPERID
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMENUTOP.OPERID
     *
     * @param operid the value for PTMENUTOP.OPERID
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMENUTOP.MENUID
     *
     * @return the value of PTMENUTOP.MENUID
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMENUTOP.MENUID
     *
     * @param menuid the value for PTMENUTOP.MENUID
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMENUTOP.VISIT_TIMES
     *
     * @return the value of PTMENUTOP.VISIT_TIMES
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    public Integer getVisitTimes() {
        return visitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMENUTOP.VISIT_TIMES
     *
     * @param visitTimes the value for PTMENUTOP.VISIT_TIMES
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    public void setVisitTimes(Integer visitTimes) {
        this.visitTimes = visitTimes;
    }
}