package skyline.repository.model;

import java.io.Serializable;

public class Ptmodule implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.MODULE_NAME
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.MODULE_LABEL
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String moduleLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.MODULE_DESC
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String moduleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.DISP_ORDER
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String dispOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.ICON1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String icon1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.ICON2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String icon2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.ICON3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String icon3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.REMARK1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.REMARK2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.REMARK3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String remark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.COLOR1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String color1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.COLOR2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String color2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTMODULE.COLOR3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    private String color3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.MODULE_NAME
     *
     * @return the value of PTMODULE.MODULE_NAME
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.MODULE_NAME
     *
     * @param moduleName the value for PTMODULE.MODULE_NAME
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.MODULE_LABEL
     *
     * @return the value of PTMODULE.MODULE_LABEL
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getModuleLabel() {
        return moduleLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.MODULE_LABEL
     *
     * @param moduleLabel the value for PTMODULE.MODULE_LABEL
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setModuleLabel(String moduleLabel) {
        this.moduleLabel = moduleLabel == null ? null : moduleLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.MODULE_DESC
     *
     * @return the value of PTMODULE.MODULE_DESC
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.MODULE_DESC
     *
     * @param moduleDesc the value for PTMODULE.MODULE_DESC
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc == null ? null : moduleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.DISP_ORDER
     *
     * @return the value of PTMODULE.DISP_ORDER
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.DISP_ORDER
     *
     * @param dispOrder the value for PTMODULE.DISP_ORDER
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setDispOrder(String dispOrder) {
        this.dispOrder = dispOrder == null ? null : dispOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.ICON1
     *
     * @return the value of PTMODULE.ICON1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getIcon1() {
        return icon1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.ICON1
     *
     * @param icon1 the value for PTMODULE.ICON1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setIcon1(String icon1) {
        this.icon1 = icon1 == null ? null : icon1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.ICON2
     *
     * @return the value of PTMODULE.ICON2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getIcon2() {
        return icon2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.ICON2
     *
     * @param icon2 the value for PTMODULE.ICON2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setIcon2(String icon2) {
        this.icon2 = icon2 == null ? null : icon2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.ICON3
     *
     * @return the value of PTMODULE.ICON3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getIcon3() {
        return icon3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.ICON3
     *
     * @param icon3 the value for PTMODULE.ICON3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setIcon3(String icon3) {
        this.icon3 = icon3 == null ? null : icon3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.REMARK1
     *
     * @return the value of PTMODULE.REMARK1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.REMARK1
     *
     * @param remark1 the value for PTMODULE.REMARK1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.REMARK2
     *
     * @return the value of PTMODULE.REMARK2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.REMARK2
     *
     * @param remark2 the value for PTMODULE.REMARK2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.REMARK3
     *
     * @return the value of PTMODULE.REMARK3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.REMARK3
     *
     * @param remark3 the value for PTMODULE.REMARK3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.COLOR1
     *
     * @return the value of PTMODULE.COLOR1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getColor1() {
        return color1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.COLOR1
     *
     * @param color1 the value for PTMODULE.COLOR1
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setColor1(String color1) {
        this.color1 = color1 == null ? null : color1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.COLOR2
     *
     * @return the value of PTMODULE.COLOR2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getColor2() {
        return color2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.COLOR2
     *
     * @param color2 the value for PTMODULE.COLOR2
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setColor2(String color2) {
        this.color2 = color2 == null ? null : color2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTMODULE.COLOR3
     *
     * @return the value of PTMODULE.COLOR3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public String getColor3() {
        return color3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTMODULE.COLOR3
     *
     * @param color3 the value for PTMODULE.COLOR3
     *
     * @mbggenerated Wed Aug 05 17:52:46 CST 2015
     */
    public void setColor3(String color3) {
        this.color3 = color3 == null ? null : color3.trim();
    }
}