package pfms.repository.model;

public class InvZzsHeadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.XSDDM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String xsddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.DMGS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String dmgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.XSDDM
     *
     * @return the value of INV_ZZS_HEAD.XSDDM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getXsddm() {
        return xsddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.XSDDM
     *
     * @param xsddm the value for INV_ZZS_HEAD.XSDDM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setXsddm(String xsddm) {
        this.xsddm = xsddm == null ? null : xsddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.DMGS
     *
     * @return the value of INV_ZZS_HEAD.DMGS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getDmgs() {
        return dmgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.DMGS
     *
     * @param dmgs the value for INV_ZZS_HEAD.DMGS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setDmgs(String dmgs) {
        this.dmgs = dmgs == null ? null : dmgs.trim();
    }
}