package pfms.repository.model;

import java.util.Date;

public class InvZzsHead extends InvZzsHeadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KHDM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String khdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KHSWDJH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String khswdjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KHMC
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String khmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KHSJ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String khsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KHDZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String khdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KHYH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String khyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.BZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.SKR
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String skr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.FHR
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String fhr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KPRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date kprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.FPZL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String fpzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.ZX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String zx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.FPHM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String fphm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.URL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.SKRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date skrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date xrrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.PZRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date pzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KPBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String kpbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.XRSJ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date xrsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.PZHXCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Short pzhxcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.PZH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String pzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.PZMESSAGE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String pzmessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.PZCLBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String pzclbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.TZDH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String tzdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.CHFPH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String chfph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.CLCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Short clcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.KP_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String kpFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.ZF_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String zfFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.CH_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String chFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.FBTIDX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String fbtidx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.DATASRC
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String datasrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.CRT_DATE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String crtDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.CRT_TIME
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.CRT_OPER_ID
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String crtOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.UPD_DATE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String updDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.UPD_TIME
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.UPD_OPER_ID
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String updOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_HEAD.PZXX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private byte[] pzxx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KHDM
     *
     * @return the value of INV_ZZS_HEAD.KHDM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKhdm() {
        return khdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KHDM
     *
     * @param khdm the value for INV_ZZS_HEAD.KHDM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKhdm(String khdm) {
        this.khdm = khdm == null ? null : khdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KHSWDJH
     *
     * @return the value of INV_ZZS_HEAD.KHSWDJH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKhswdjh() {
        return khswdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KHSWDJH
     *
     * @param khswdjh the value for INV_ZZS_HEAD.KHSWDJH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKhswdjh(String khswdjh) {
        this.khswdjh = khswdjh == null ? null : khswdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KHMC
     *
     * @return the value of INV_ZZS_HEAD.KHMC
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKhmc() {
        return khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KHMC
     *
     * @param khmc the value for INV_ZZS_HEAD.KHMC
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKhmc(String khmc) {
        this.khmc = khmc == null ? null : khmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KHSJ
     *
     * @return the value of INV_ZZS_HEAD.KHSJ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKhsj() {
        return khsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KHSJ
     *
     * @param khsj the value for INV_ZZS_HEAD.KHSJ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKhsj(String khsj) {
        this.khsj = khsj == null ? null : khsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KHDZ
     *
     * @return the value of INV_ZZS_HEAD.KHDZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKhdz() {
        return khdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KHDZ
     *
     * @param khdz the value for INV_ZZS_HEAD.KHDZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKhdz(String khdz) {
        this.khdz = khdz == null ? null : khdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KHYH
     *
     * @return the value of INV_ZZS_HEAD.KHYH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKhyh() {
        return khyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KHYH
     *
     * @param khyh the value for INV_ZZS_HEAD.KHYH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKhyh(String khyh) {
        this.khyh = khyh == null ? null : khyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.BZ
     *
     * @return the value of INV_ZZS_HEAD.BZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.BZ
     *
     * @param bz the value for INV_ZZS_HEAD.BZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.SKR
     *
     * @return the value of INV_ZZS_HEAD.SKR
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getSkr() {
        return skr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.SKR
     *
     * @param skr the value for INV_ZZS_HEAD.SKR
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setSkr(String skr) {
        this.skr = skr == null ? null : skr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.FHR
     *
     * @return the value of INV_ZZS_HEAD.FHR
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getFhr() {
        return fhr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.FHR
     *
     * @param fhr the value for INV_ZZS_HEAD.FHR
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setFhr(String fhr) {
        this.fhr = fhr == null ? null : fhr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KPRQ
     *
     * @return the value of INV_ZZS_HEAD.KPRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getKprq() {
        return kprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KPRQ
     *
     * @param kprq the value for INV_ZZS_HEAD.KPRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKprq(Date kprq) {
        this.kprq = kprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.FPZL
     *
     * @return the value of INV_ZZS_HEAD.FPZL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getFpzl() {
        return fpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.FPZL
     *
     * @param fpzl the value for INV_ZZS_HEAD.FPZL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setFpzl(String fpzl) {
        this.fpzl = fpzl == null ? null : fpzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.ZX
     *
     * @return the value of INV_ZZS_HEAD.ZX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getZx() {
        return zx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.ZX
     *
     * @param zx the value for INV_ZZS_HEAD.ZX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setZx(String zx) {
        this.zx = zx == null ? null : zx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.FPHM
     *
     * @return the value of INV_ZZS_HEAD.FPHM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getFphm() {
        return fphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.FPHM
     *
     * @param fphm the value for INV_ZZS_HEAD.FPHM
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setFphm(String fphm) {
        this.fphm = fphm == null ? null : fphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.MSG
     *
     * @return the value of INV_ZZS_HEAD.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.MSG
     *
     * @param msg the value for INV_ZZS_HEAD.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.URL
     *
     * @return the value of INV_ZZS_HEAD.URL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.URL
     *
     * @param url the value for INV_ZZS_HEAD.URL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.SKRQ
     *
     * @return the value of INV_ZZS_HEAD.SKRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getSkrq() {
        return skrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.SKRQ
     *
     * @param skrq the value for INV_ZZS_HEAD.SKRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setSkrq(Date skrq) {
        this.skrq = skrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.XRRQ
     *
     * @return the value of INV_ZZS_HEAD.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getXrrq() {
        return xrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.XRRQ
     *
     * @param xrrq the value for INV_ZZS_HEAD.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setXrrq(Date xrrq) {
        this.xrrq = xrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.PZRQ
     *
     * @return the value of INV_ZZS_HEAD.PZRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getPzrq() {
        return pzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.PZRQ
     *
     * @param pzrq the value for INV_ZZS_HEAD.PZRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setPzrq(Date pzrq) {
        this.pzrq = pzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KPBZ
     *
     * @return the value of INV_ZZS_HEAD.KPBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKpbz() {
        return kpbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KPBZ
     *
     * @param kpbz the value for INV_ZZS_HEAD.KPBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKpbz(String kpbz) {
        this.kpbz = kpbz == null ? null : kpbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.XRSJ
     *
     * @return the value of INV_ZZS_HEAD.XRSJ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getXrsj() {
        return xrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.XRSJ
     *
     * @param xrsj the value for INV_ZZS_HEAD.XRSJ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setXrsj(Date xrsj) {
        this.xrsj = xrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.PZHXCS
     *
     * @return the value of INV_ZZS_HEAD.PZHXCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Short getPzhxcs() {
        return pzhxcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.PZHXCS
     *
     * @param pzhxcs the value for INV_ZZS_HEAD.PZHXCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setPzhxcs(Short pzhxcs) {
        this.pzhxcs = pzhxcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.PZH
     *
     * @return the value of INV_ZZS_HEAD.PZH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getPzh() {
        return pzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.PZH
     *
     * @param pzh the value for INV_ZZS_HEAD.PZH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setPzh(String pzh) {
        this.pzh = pzh == null ? null : pzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.PZMESSAGE
     *
     * @return the value of INV_ZZS_HEAD.PZMESSAGE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getPzmessage() {
        return pzmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.PZMESSAGE
     *
     * @param pzmessage the value for INV_ZZS_HEAD.PZMESSAGE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setPzmessage(String pzmessage) {
        this.pzmessage = pzmessage == null ? null : pzmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.PZCLBZ
     *
     * @return the value of INV_ZZS_HEAD.PZCLBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getPzclbz() {
        return pzclbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.PZCLBZ
     *
     * @param pzclbz the value for INV_ZZS_HEAD.PZCLBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setPzclbz(String pzclbz) {
        this.pzclbz = pzclbz == null ? null : pzclbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.TZDH
     *
     * @return the value of INV_ZZS_HEAD.TZDH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getTzdh() {
        return tzdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.TZDH
     *
     * @param tzdh the value for INV_ZZS_HEAD.TZDH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setTzdh(String tzdh) {
        this.tzdh = tzdh == null ? null : tzdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.CHFPH
     *
     * @return the value of INV_ZZS_HEAD.CHFPH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getChfph() {
        return chfph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.CHFPH
     *
     * @param chfph the value for INV_ZZS_HEAD.CHFPH
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setChfph(String chfph) {
        this.chfph = chfph == null ? null : chfph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.CLCS
     *
     * @return the value of INV_ZZS_HEAD.CLCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Short getClcs() {
        return clcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.CLCS
     *
     * @param clcs the value for INV_ZZS_HEAD.CLCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setClcs(Short clcs) {
        this.clcs = clcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.KP_FLAG
     *
     * @return the value of INV_ZZS_HEAD.KP_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getKpFlag() {
        return kpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.KP_FLAG
     *
     * @param kpFlag the value for INV_ZZS_HEAD.KP_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKpFlag(String kpFlag) {
        this.kpFlag = kpFlag == null ? null : kpFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.ZF_FLAG
     *
     * @return the value of INV_ZZS_HEAD.ZF_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getZfFlag() {
        return zfFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.ZF_FLAG
     *
     * @param zfFlag the value for INV_ZZS_HEAD.ZF_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setZfFlag(String zfFlag) {
        this.zfFlag = zfFlag == null ? null : zfFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.CH_FLAG
     *
     * @return the value of INV_ZZS_HEAD.CH_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getChFlag() {
        return chFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.CH_FLAG
     *
     * @param chFlag the value for INV_ZZS_HEAD.CH_FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setChFlag(String chFlag) {
        this.chFlag = chFlag == null ? null : chFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.FBTIDX
     *
     * @return the value of INV_ZZS_HEAD.FBTIDX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getFbtidx() {
        return fbtidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.FBTIDX
     *
     * @param fbtidx the value for INV_ZZS_HEAD.FBTIDX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setFbtidx(String fbtidx) {
        this.fbtidx = fbtidx == null ? null : fbtidx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.DATASRC
     *
     * @return the value of INV_ZZS_HEAD.DATASRC
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getDatasrc() {
        return datasrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.DATASRC
     *
     * @param datasrc the value for INV_ZZS_HEAD.DATASRC
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setDatasrc(String datasrc) {
        this.datasrc = datasrc == null ? null : datasrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.CRT_DATE
     *
     * @return the value of INV_ZZS_HEAD.CRT_DATE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.CRT_DATE
     *
     * @param crtDate the value for INV_ZZS_HEAD.CRT_DATE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setCrtDate(String crtDate) {
        this.crtDate = crtDate == null ? null : crtDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.CRT_TIME
     *
     * @return the value of INV_ZZS_HEAD.CRT_TIME
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.CRT_TIME
     *
     * @param crtTime the value for INV_ZZS_HEAD.CRT_TIME
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setCrtTime(String crtTime) {
        this.crtTime = crtTime == null ? null : crtTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.CRT_OPER_ID
     *
     * @return the value of INV_ZZS_HEAD.CRT_OPER_ID
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getCrtOperId() {
        return crtOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.CRT_OPER_ID
     *
     * @param crtOperId the value for INV_ZZS_HEAD.CRT_OPER_ID
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setCrtOperId(String crtOperId) {
        this.crtOperId = crtOperId == null ? null : crtOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.UPD_DATE
     *
     * @return the value of INV_ZZS_HEAD.UPD_DATE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.UPD_DATE
     *
     * @param updDate the value for INV_ZZS_HEAD.UPD_DATE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setUpdDate(String updDate) {
        this.updDate = updDate == null ? null : updDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.UPD_TIME
     *
     * @return the value of INV_ZZS_HEAD.UPD_TIME
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.UPD_TIME
     *
     * @param updTime the value for INV_ZZS_HEAD.UPD_TIME
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setUpdTime(String updTime) {
        this.updTime = updTime == null ? null : updTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.UPD_OPER_ID
     *
     * @return the value of INV_ZZS_HEAD.UPD_OPER_ID
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getUpdOperId() {
        return updOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.UPD_OPER_ID
     *
     * @param updOperId the value for INV_ZZS_HEAD.UPD_OPER_ID
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setUpdOperId(String updOperId) {
        this.updOperId = updOperId == null ? null : updOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_HEAD.PZXX
     *
     * @return the value of INV_ZZS_HEAD.PZXX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public byte[] getPzxx() {
        return pzxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_HEAD.PZXX
     *
     * @param pzxx the value for INV_ZZS_HEAD.PZXX
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setPzxx(byte[] pzxx) {
        this.pzxx = pzxx;
    }
}