package pfms.repository.model;

public class InvZzsSyncFailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SYNC_FAIL.TXN_DATE
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SYNC_FAIL.DATASRC
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    private String datasrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SYNC_FAIL.TXN_DATE
     *
     * @return the value of INV_ZZS_SYNC_FAIL.TXN_DATE
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SYNC_FAIL.TXN_DATE
     *
     * @param txnDate the value for INV_ZZS_SYNC_FAIL.TXN_DATE
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SYNC_FAIL.DATASRC
     *
     * @return the value of INV_ZZS_SYNC_FAIL.DATASRC
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    public String getDatasrc() {
        return datasrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SYNC_FAIL.DATASRC
     *
     * @param datasrc the value for INV_ZZS_SYNC_FAIL.DATASRC
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    public void setDatasrc(String datasrc) {
        this.datasrc = datasrc == null ? null : datasrc.trim();
    }
}