package pfms.repository.model;

import java.math.BigDecimal;

public class InvZzsSrc extends InvZzsSrcKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.KHDM
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String khdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CPDM
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String cpdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CPMC
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String cpmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.XH
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CPDW
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String cpdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CPSL
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal cpsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.HSDJ
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal hsdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.HSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal hsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.XXDJ
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal xxdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.BHSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal bhsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.SE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal se;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.SL
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.ZBHSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal zbhsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.ZSE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private BigDecimal zse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CRT_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String crtDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CRT_TIME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.CRT_OPER_ID
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String crtOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.UPD_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String updDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.UPD_TIME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.UPD_OPER_ID
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String updOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.PRINT_FLAG
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String printFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.PROC_FLAG
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String procFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.TXN_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_SRC.PAYER_NAME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    private String payerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.KHDM
     *
     * @return the value of INV_ZZS_SRC.KHDM
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getKhdm() {
        return khdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.KHDM
     *
     * @param khdm the value for INV_ZZS_SRC.KHDM
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setKhdm(String khdm) {
        this.khdm = khdm == null ? null : khdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CPDM
     *
     * @return the value of INV_ZZS_SRC.CPDM
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getCpdm() {
        return cpdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CPDM
     *
     * @param cpdm the value for INV_ZZS_SRC.CPDM
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCpdm(String cpdm) {
        this.cpdm = cpdm == null ? null : cpdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CPMC
     *
     * @return the value of INV_ZZS_SRC.CPMC
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getCpmc() {
        return cpmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CPMC
     *
     * @param cpmc the value for INV_ZZS_SRC.CPMC
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCpmc(String cpmc) {
        this.cpmc = cpmc == null ? null : cpmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.XH
     *
     * @return the value of INV_ZZS_SRC.XH
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.XH
     *
     * @param xh the value for INV_ZZS_SRC.XH
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CPDW
     *
     * @return the value of INV_ZZS_SRC.CPDW
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getCpdw() {
        return cpdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CPDW
     *
     * @param cpdw the value for INV_ZZS_SRC.CPDW
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCpdw(String cpdw) {
        this.cpdw = cpdw == null ? null : cpdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CPSL
     *
     * @return the value of INV_ZZS_SRC.CPSL
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getCpsl() {
        return cpsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CPSL
     *
     * @param cpsl the value for INV_ZZS_SRC.CPSL
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCpsl(BigDecimal cpsl) {
        this.cpsl = cpsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.HSDJ
     *
     * @return the value of INV_ZZS_SRC.HSDJ
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getHsdj() {
        return hsdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.HSDJ
     *
     * @param hsdj the value for INV_ZZS_SRC.HSDJ
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setHsdj(BigDecimal hsdj) {
        this.hsdj = hsdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.HSJE
     *
     * @return the value of INV_ZZS_SRC.HSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getHsje() {
        return hsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.HSJE
     *
     * @param hsje the value for INV_ZZS_SRC.HSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setHsje(BigDecimal hsje) {
        this.hsje = hsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.XXDJ
     *
     * @return the value of INV_ZZS_SRC.XXDJ
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getXxdj() {
        return xxdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.XXDJ
     *
     * @param xxdj the value for INV_ZZS_SRC.XXDJ
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setXxdj(BigDecimal xxdj) {
        this.xxdj = xxdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.BHSJE
     *
     * @return the value of INV_ZZS_SRC.BHSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getBhsje() {
        return bhsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.BHSJE
     *
     * @param bhsje the value for INV_ZZS_SRC.BHSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setBhsje(BigDecimal bhsje) {
        this.bhsje = bhsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.SE
     *
     * @return the value of INV_ZZS_SRC.SE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getSe() {
        return se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.SE
     *
     * @param se the value for INV_ZZS_SRC.SE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setSe(BigDecimal se) {
        this.se = se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.SL
     *
     * @return the value of INV_ZZS_SRC.SL
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.SL
     *
     * @param sl the value for INV_ZZS_SRC.SL
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.ZBHSJE
     *
     * @return the value of INV_ZZS_SRC.ZBHSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getZbhsje() {
        return zbhsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.ZBHSJE
     *
     * @param zbhsje the value for INV_ZZS_SRC.ZBHSJE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setZbhsje(BigDecimal zbhsje) {
        this.zbhsje = zbhsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.ZSE
     *
     * @return the value of INV_ZZS_SRC.ZSE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public BigDecimal getZse() {
        return zse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.ZSE
     *
     * @param zse the value for INV_ZZS_SRC.ZSE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setZse(BigDecimal zse) {
        this.zse = zse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CRT_DATE
     *
     * @return the value of INV_ZZS_SRC.CRT_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CRT_DATE
     *
     * @param crtDate the value for INV_ZZS_SRC.CRT_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCrtDate(String crtDate) {
        this.crtDate = crtDate == null ? null : crtDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CRT_TIME
     *
     * @return the value of INV_ZZS_SRC.CRT_TIME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CRT_TIME
     *
     * @param crtTime the value for INV_ZZS_SRC.CRT_TIME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCrtTime(String crtTime) {
        this.crtTime = crtTime == null ? null : crtTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.CRT_OPER_ID
     *
     * @return the value of INV_ZZS_SRC.CRT_OPER_ID
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getCrtOperId() {
        return crtOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.CRT_OPER_ID
     *
     * @param crtOperId the value for INV_ZZS_SRC.CRT_OPER_ID
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setCrtOperId(String crtOperId) {
        this.crtOperId = crtOperId == null ? null : crtOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.UPD_DATE
     *
     * @return the value of INV_ZZS_SRC.UPD_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.UPD_DATE
     *
     * @param updDate the value for INV_ZZS_SRC.UPD_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setUpdDate(String updDate) {
        this.updDate = updDate == null ? null : updDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.UPD_TIME
     *
     * @return the value of INV_ZZS_SRC.UPD_TIME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.UPD_TIME
     *
     * @param updTime the value for INV_ZZS_SRC.UPD_TIME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setUpdTime(String updTime) {
        this.updTime = updTime == null ? null : updTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.UPD_OPER_ID
     *
     * @return the value of INV_ZZS_SRC.UPD_OPER_ID
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getUpdOperId() {
        return updOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.UPD_OPER_ID
     *
     * @param updOperId the value for INV_ZZS_SRC.UPD_OPER_ID
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setUpdOperId(String updOperId) {
        this.updOperId = updOperId == null ? null : updOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.PRINT_FLAG
     *
     * @return the value of INV_ZZS_SRC.PRINT_FLAG
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getPrintFlag() {
        return printFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.PRINT_FLAG
     *
     * @param printFlag the value for INV_ZZS_SRC.PRINT_FLAG
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setPrintFlag(String printFlag) {
        this.printFlag = printFlag == null ? null : printFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.PROC_FLAG
     *
     * @return the value of INV_ZZS_SRC.PROC_FLAG
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getProcFlag() {
        return procFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.PROC_FLAG
     *
     * @param procFlag the value for INV_ZZS_SRC.PROC_FLAG
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setProcFlag(String procFlag) {
        this.procFlag = procFlag == null ? null : procFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.TXN_DATE
     *
     * @return the value of INV_ZZS_SRC.TXN_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.TXN_DATE
     *
     * @param txnDate the value for INV_ZZS_SRC.TXN_DATE
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_SRC.PAYER_NAME
     *
     * @return the value of INV_ZZS_SRC.PAYER_NAME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_SRC.PAYER_NAME
     *
     * @param payerName the value for INV_ZZS_SRC.PAYER_NAME
     *
     * @mbggenerated Thu Apr 28 11:32:24 CST 2016
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }
}