package pfms.repository.model;

import java.util.Date;

public class InvZzsZfhx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.INVOICECODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String invoicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.KPRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date kprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.RELATEDCODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String relatedcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.VIEWURL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String viewurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.TAG1
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String tag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.TAG2
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String tag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZFHX.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date xrrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.INVOICECODE
     *
     * @return the value of INV_ZZS_ZFHX.INVOICECODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getInvoicecode() {
        return invoicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.INVOICECODE
     *
     * @param invoicecode the value for INV_ZZS_ZFHX.INVOICECODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setInvoicecode(String invoicecode) {
        this.invoicecode = invoicecode == null ? null : invoicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.FLAG
     *
     * @return the value of INV_ZZS_ZFHX.FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.FLAG
     *
     * @param flag the value for INV_ZZS_ZFHX.FLAG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.KPRQ
     *
     * @return the value of INV_ZZS_ZFHX.KPRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getKprq() {
        return kprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.KPRQ
     *
     * @param kprq the value for INV_ZZS_ZFHX.KPRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setKprq(Date kprq) {
        this.kprq = kprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.RELATEDCODE
     *
     * @return the value of INV_ZZS_ZFHX.RELATEDCODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getRelatedcode() {
        return relatedcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.RELATEDCODE
     *
     * @param relatedcode the value for INV_ZZS_ZFHX.RELATEDCODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setRelatedcode(String relatedcode) {
        this.relatedcode = relatedcode == null ? null : relatedcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.VIEWURL
     *
     * @return the value of INV_ZZS_ZFHX.VIEWURL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getViewurl() {
        return viewurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.VIEWURL
     *
     * @param viewurl the value for INV_ZZS_ZFHX.VIEWURL
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setViewurl(String viewurl) {
        this.viewurl = viewurl == null ? null : viewurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.TAG1
     *
     * @return the value of INV_ZZS_ZFHX.TAG1
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getTag1() {
        return tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.TAG1
     *
     * @param tag1 the value for INV_ZZS_ZFHX.TAG1
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setTag1(String tag1) {
        this.tag1 = tag1 == null ? null : tag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.TAG2
     *
     * @return the value of INV_ZZS_ZFHX.TAG2
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getTag2() {
        return tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.TAG2
     *
     * @param tag2 the value for INV_ZZS_ZFHX.TAG2
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setTag2(String tag2) {
        this.tag2 = tag2 == null ? null : tag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.MSG
     *
     * @return the value of INV_ZZS_ZFHX.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.MSG
     *
     * @param msg the value for INV_ZZS_ZFHX.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZFHX.XRRQ
     *
     * @return the value of INV_ZZS_ZFHX.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getXrrq() {
        return xrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZFHX.XRRQ
     *
     * @param xrrq the value for INV_ZZS_ZFHX.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setXrrq(Date xrrq) {
        this.xrrq = xrrq;
    }
}