package pfms.repository.model;

public class InvZzsCust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.PKID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.KHDM
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String khdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.KHSWDJH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String khswdjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.KHMC
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String khmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.KHSJ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String khsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.KHDZ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String khdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.KHYH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String khyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.YHZH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String yhzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.YBNSR
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String ybnsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.BZ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.CRT_DATE
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String crtDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.CRT_TIME
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.CRT_OPER_ID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String crtOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.UPD_DATE
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String updDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.UPD_TIME
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_CUST.UPD_OPER_ID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    private String updOperId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.PKID
     *
     * @return the value of INV_ZZS_CUST.PKID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.PKID
     *
     * @param pkid the value for INV_ZZS_CUST.PKID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.KHDM
     *
     * @return the value of INV_ZZS_CUST.KHDM
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getKhdm() {
        return khdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.KHDM
     *
     * @param khdm the value for INV_ZZS_CUST.KHDM
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setKhdm(String khdm) {
        this.khdm = khdm == null ? null : khdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.KHSWDJH
     *
     * @return the value of INV_ZZS_CUST.KHSWDJH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getKhswdjh() {
        return khswdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.KHSWDJH
     *
     * @param khswdjh the value for INV_ZZS_CUST.KHSWDJH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setKhswdjh(String khswdjh) {
        this.khswdjh = khswdjh == null ? null : khswdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.KHMC
     *
     * @return the value of INV_ZZS_CUST.KHMC
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getKhmc() {
        return khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.KHMC
     *
     * @param khmc the value for INV_ZZS_CUST.KHMC
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setKhmc(String khmc) {
        this.khmc = khmc == null ? null : khmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.KHSJ
     *
     * @return the value of INV_ZZS_CUST.KHSJ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getKhsj() {
        return khsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.KHSJ
     *
     * @param khsj the value for INV_ZZS_CUST.KHSJ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setKhsj(String khsj) {
        this.khsj = khsj == null ? null : khsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.KHDZ
     *
     * @return the value of INV_ZZS_CUST.KHDZ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getKhdz() {
        return khdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.KHDZ
     *
     * @param khdz the value for INV_ZZS_CUST.KHDZ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setKhdz(String khdz) {
        this.khdz = khdz == null ? null : khdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.KHYH
     *
     * @return the value of INV_ZZS_CUST.KHYH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getKhyh() {
        return khyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.KHYH
     *
     * @param khyh the value for INV_ZZS_CUST.KHYH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setKhyh(String khyh) {
        this.khyh = khyh == null ? null : khyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.YHZH
     *
     * @return the value of INV_ZZS_CUST.YHZH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getYhzh() {
        return yhzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.YHZH
     *
     * @param yhzh the value for INV_ZZS_CUST.YHZH
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setYhzh(String yhzh) {
        this.yhzh = yhzh == null ? null : yhzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.YBNSR
     *
     * @return the value of INV_ZZS_CUST.YBNSR
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getYbnsr() {
        return ybnsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.YBNSR
     *
     * @param ybnsr the value for INV_ZZS_CUST.YBNSR
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setYbnsr(String ybnsr) {
        this.ybnsr = ybnsr == null ? null : ybnsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.BZ
     *
     * @return the value of INV_ZZS_CUST.BZ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.BZ
     *
     * @param bz the value for INV_ZZS_CUST.BZ
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.CRT_DATE
     *
     * @return the value of INV_ZZS_CUST.CRT_DATE
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.CRT_DATE
     *
     * @param crtDate the value for INV_ZZS_CUST.CRT_DATE
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setCrtDate(String crtDate) {
        this.crtDate = crtDate == null ? null : crtDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.CRT_TIME
     *
     * @return the value of INV_ZZS_CUST.CRT_TIME
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.CRT_TIME
     *
     * @param crtTime the value for INV_ZZS_CUST.CRT_TIME
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setCrtTime(String crtTime) {
        this.crtTime = crtTime == null ? null : crtTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.CRT_OPER_ID
     *
     * @return the value of INV_ZZS_CUST.CRT_OPER_ID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getCrtOperId() {
        return crtOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.CRT_OPER_ID
     *
     * @param crtOperId the value for INV_ZZS_CUST.CRT_OPER_ID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setCrtOperId(String crtOperId) {
        this.crtOperId = crtOperId == null ? null : crtOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.UPD_DATE
     *
     * @return the value of INV_ZZS_CUST.UPD_DATE
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.UPD_DATE
     *
     * @param updDate the value for INV_ZZS_CUST.UPD_DATE
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setUpdDate(String updDate) {
        this.updDate = updDate == null ? null : updDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.UPD_TIME
     *
     * @return the value of INV_ZZS_CUST.UPD_TIME
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.UPD_TIME
     *
     * @param updTime the value for INV_ZZS_CUST.UPD_TIME
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setUpdTime(String updTime) {
        this.updTime = updTime == null ? null : updTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_CUST.UPD_OPER_ID
     *
     * @return the value of INV_ZZS_CUST.UPD_OPER_ID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getUpdOperId() {
        return updOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_CUST.UPD_OPER_ID
     *
     * @param updOperId the value for INV_ZZS_CUST.UPD_OPER_ID
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setUpdOperId(String updOperId) {
        this.updOperId = updOperId == null ? null : updOperId.trim();
    }
}