package pfms.repository.model;

import java.util.ArrayList;
import java.util.List;

public class InvZzsCustExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public InvZzsCustExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andKhdmIsNull() {
            addCriterion("KHDM is null");
            return (Criteria) this;
        }

        public Criteria andKhdmIsNotNull() {
            addCriterion("KHDM is not null");
            return (Criteria) this;
        }

        public Criteria andKhdmEqualTo(String value) {
            addCriterion("KHDM =", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmNotEqualTo(String value) {
            addCriterion("KHDM <>", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmGreaterThan(String value) {
            addCriterion("KHDM >", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmGreaterThanOrEqualTo(String value) {
            addCriterion("KHDM >=", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmLessThan(String value) {
            addCriterion("KHDM <", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmLessThanOrEqualTo(String value) {
            addCriterion("KHDM <=", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmLike(String value) {
            addCriterion("KHDM like", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmNotLike(String value) {
            addCriterion("KHDM not like", value, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmIn(List<String> values) {
            addCriterion("KHDM in", values, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmNotIn(List<String> values) {
            addCriterion("KHDM not in", values, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmBetween(String value1, String value2) {
            addCriterion("KHDM between", value1, value2, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhdmNotBetween(String value1, String value2) {
            addCriterion("KHDM not between", value1, value2, "khdm");
            return (Criteria) this;
        }

        public Criteria andKhswdjhIsNull() {
            addCriterion("KHSWDJH is null");
            return (Criteria) this;
        }

        public Criteria andKhswdjhIsNotNull() {
            addCriterion("KHSWDJH is not null");
            return (Criteria) this;
        }

        public Criteria andKhswdjhEqualTo(String value) {
            addCriterion("KHSWDJH =", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhNotEqualTo(String value) {
            addCriterion("KHSWDJH <>", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhGreaterThan(String value) {
            addCriterion("KHSWDJH >", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhGreaterThanOrEqualTo(String value) {
            addCriterion("KHSWDJH >=", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhLessThan(String value) {
            addCriterion("KHSWDJH <", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhLessThanOrEqualTo(String value) {
            addCriterion("KHSWDJH <=", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhLike(String value) {
            addCriterion("KHSWDJH like", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhNotLike(String value) {
            addCriterion("KHSWDJH not like", value, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhIn(List<String> values) {
            addCriterion("KHSWDJH in", values, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhNotIn(List<String> values) {
            addCriterion("KHSWDJH not in", values, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhBetween(String value1, String value2) {
            addCriterion("KHSWDJH between", value1, value2, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhswdjhNotBetween(String value1, String value2) {
            addCriterion("KHSWDJH not between", value1, value2, "khswdjh");
            return (Criteria) this;
        }

        public Criteria andKhmcIsNull() {
            addCriterion("KHMC is null");
            return (Criteria) this;
        }

        public Criteria andKhmcIsNotNull() {
            addCriterion("KHMC is not null");
            return (Criteria) this;
        }

        public Criteria andKhmcEqualTo(String value) {
            addCriterion("KHMC =", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotEqualTo(String value) {
            addCriterion("KHMC <>", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcGreaterThan(String value) {
            addCriterion("KHMC >", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcGreaterThanOrEqualTo(String value) {
            addCriterion("KHMC >=", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcLessThan(String value) {
            addCriterion("KHMC <", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcLessThanOrEqualTo(String value) {
            addCriterion("KHMC <=", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcLike(String value) {
            addCriterion("KHMC like", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotLike(String value) {
            addCriterion("KHMC not like", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcIn(List<String> values) {
            addCriterion("KHMC in", values, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotIn(List<String> values) {
            addCriterion("KHMC not in", values, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcBetween(String value1, String value2) {
            addCriterion("KHMC between", value1, value2, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotBetween(String value1, String value2) {
            addCriterion("KHMC not between", value1, value2, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhsjIsNull() {
            addCriterion("KHSJ is null");
            return (Criteria) this;
        }

        public Criteria andKhsjIsNotNull() {
            addCriterion("KHSJ is not null");
            return (Criteria) this;
        }

        public Criteria andKhsjEqualTo(String value) {
            addCriterion("KHSJ =", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjNotEqualTo(String value) {
            addCriterion("KHSJ <>", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjGreaterThan(String value) {
            addCriterion("KHSJ >", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjGreaterThanOrEqualTo(String value) {
            addCriterion("KHSJ >=", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjLessThan(String value) {
            addCriterion("KHSJ <", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjLessThanOrEqualTo(String value) {
            addCriterion("KHSJ <=", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjLike(String value) {
            addCriterion("KHSJ like", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjNotLike(String value) {
            addCriterion("KHSJ not like", value, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjIn(List<String> values) {
            addCriterion("KHSJ in", values, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjNotIn(List<String> values) {
            addCriterion("KHSJ not in", values, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjBetween(String value1, String value2) {
            addCriterion("KHSJ between", value1, value2, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhsjNotBetween(String value1, String value2) {
            addCriterion("KHSJ not between", value1, value2, "khsj");
            return (Criteria) this;
        }

        public Criteria andKhdzIsNull() {
            addCriterion("KHDZ is null");
            return (Criteria) this;
        }

        public Criteria andKhdzIsNotNull() {
            addCriterion("KHDZ is not null");
            return (Criteria) this;
        }

        public Criteria andKhdzEqualTo(String value) {
            addCriterion("KHDZ =", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzNotEqualTo(String value) {
            addCriterion("KHDZ <>", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzGreaterThan(String value) {
            addCriterion("KHDZ >", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzGreaterThanOrEqualTo(String value) {
            addCriterion("KHDZ >=", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzLessThan(String value) {
            addCriterion("KHDZ <", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzLessThanOrEqualTo(String value) {
            addCriterion("KHDZ <=", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzLike(String value) {
            addCriterion("KHDZ like", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzNotLike(String value) {
            addCriterion("KHDZ not like", value, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzIn(List<String> values) {
            addCriterion("KHDZ in", values, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzNotIn(List<String> values) {
            addCriterion("KHDZ not in", values, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzBetween(String value1, String value2) {
            addCriterion("KHDZ between", value1, value2, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhdzNotBetween(String value1, String value2) {
            addCriterion("KHDZ not between", value1, value2, "khdz");
            return (Criteria) this;
        }

        public Criteria andKhyhIsNull() {
            addCriterion("KHYH is null");
            return (Criteria) this;
        }

        public Criteria andKhyhIsNotNull() {
            addCriterion("KHYH is not null");
            return (Criteria) this;
        }

        public Criteria andKhyhEqualTo(String value) {
            addCriterion("KHYH =", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhNotEqualTo(String value) {
            addCriterion("KHYH <>", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhGreaterThan(String value) {
            addCriterion("KHYH >", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhGreaterThanOrEqualTo(String value) {
            addCriterion("KHYH >=", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhLessThan(String value) {
            addCriterion("KHYH <", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhLessThanOrEqualTo(String value) {
            addCriterion("KHYH <=", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhLike(String value) {
            addCriterion("KHYH like", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhNotLike(String value) {
            addCriterion("KHYH not like", value, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhIn(List<String> values) {
            addCriterion("KHYH in", values, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhNotIn(List<String> values) {
            addCriterion("KHYH not in", values, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhBetween(String value1, String value2) {
            addCriterion("KHYH between", value1, value2, "khyh");
            return (Criteria) this;
        }

        public Criteria andKhyhNotBetween(String value1, String value2) {
            addCriterion("KHYH not between", value1, value2, "khyh");
            return (Criteria) this;
        }

        public Criteria andYhzhIsNull() {
            addCriterion("YHZH is null");
            return (Criteria) this;
        }

        public Criteria andYhzhIsNotNull() {
            addCriterion("YHZH is not null");
            return (Criteria) this;
        }

        public Criteria andYhzhEqualTo(String value) {
            addCriterion("YHZH =", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhNotEqualTo(String value) {
            addCriterion("YHZH <>", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhGreaterThan(String value) {
            addCriterion("YHZH >", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhGreaterThanOrEqualTo(String value) {
            addCriterion("YHZH >=", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhLessThan(String value) {
            addCriterion("YHZH <", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhLessThanOrEqualTo(String value) {
            addCriterion("YHZH <=", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhLike(String value) {
            addCriterion("YHZH like", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhNotLike(String value) {
            addCriterion("YHZH not like", value, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhIn(List<String> values) {
            addCriterion("YHZH in", values, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhNotIn(List<String> values) {
            addCriterion("YHZH not in", values, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhBetween(String value1, String value2) {
            addCriterion("YHZH between", value1, value2, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYhzhNotBetween(String value1, String value2) {
            addCriterion("YHZH not between", value1, value2, "yhzh");
            return (Criteria) this;
        }

        public Criteria andYbnsrIsNull() {
            addCriterion("YBNSR is null");
            return (Criteria) this;
        }

        public Criteria andYbnsrIsNotNull() {
            addCriterion("YBNSR is not null");
            return (Criteria) this;
        }

        public Criteria andYbnsrEqualTo(String value) {
            addCriterion("YBNSR =", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrNotEqualTo(String value) {
            addCriterion("YBNSR <>", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrGreaterThan(String value) {
            addCriterion("YBNSR >", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrGreaterThanOrEqualTo(String value) {
            addCriterion("YBNSR >=", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrLessThan(String value) {
            addCriterion("YBNSR <", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrLessThanOrEqualTo(String value) {
            addCriterion("YBNSR <=", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrLike(String value) {
            addCriterion("YBNSR like", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrNotLike(String value) {
            addCriterion("YBNSR not like", value, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrIn(List<String> values) {
            addCriterion("YBNSR in", values, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrNotIn(List<String> values) {
            addCriterion("YBNSR not in", values, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrBetween(String value1, String value2) {
            addCriterion("YBNSR between", value1, value2, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andYbnsrNotBetween(String value1, String value2) {
            addCriterion("YBNSR not between", value1, value2, "ybnsr");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andCrtDateIsNull() {
            addCriterion("CRT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCrtDateIsNotNull() {
            addCriterion("CRT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDateEqualTo(String value) {
            addCriterion("CRT_DATE =", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotEqualTo(String value) {
            addCriterion("CRT_DATE <>", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateGreaterThan(String value) {
            addCriterion("CRT_DATE >", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_DATE >=", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateLessThan(String value) {
            addCriterion("CRT_DATE <", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateLessThanOrEqualTo(String value) {
            addCriterion("CRT_DATE <=", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateLike(String value) {
            addCriterion("CRT_DATE like", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotLike(String value) {
            addCriterion("CRT_DATE not like", value, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateIn(List<String> values) {
            addCriterion("CRT_DATE in", values, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotIn(List<String> values) {
            addCriterion("CRT_DATE not in", values, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateBetween(String value1, String value2) {
            addCriterion("CRT_DATE between", value1, value2, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtDateNotBetween(String value1, String value2) {
            addCriterion("CRT_DATE not between", value1, value2, "crtDate");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("CRT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("CRT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(String value) {
            addCriterion("CRT_TIME =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(String value) {
            addCriterion("CRT_TIME <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(String value) {
            addCriterion("CRT_TIME >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_TIME >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(String value) {
            addCriterion("CRT_TIME <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(String value) {
            addCriterion("CRT_TIME <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLike(String value) {
            addCriterion("CRT_TIME like", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotLike(String value) {
            addCriterion("CRT_TIME not like", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<String> values) {
            addCriterion("CRT_TIME in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<String> values) {
            addCriterion("CRT_TIME not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(String value1, String value2) {
            addCriterion("CRT_TIME between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(String value1, String value2) {
            addCriterion("CRT_TIME not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdIsNull() {
            addCriterion("CRT_OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdIsNotNull() {
            addCriterion("CRT_OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdEqualTo(String value) {
            addCriterion("CRT_OPER_ID =", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotEqualTo(String value) {
            addCriterion("CRT_OPER_ID <>", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdGreaterThan(String value) {
            addCriterion("CRT_OPER_ID >", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_OPER_ID >=", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdLessThan(String value) {
            addCriterion("CRT_OPER_ID <", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdLessThanOrEqualTo(String value) {
            addCriterion("CRT_OPER_ID <=", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdLike(String value) {
            addCriterion("CRT_OPER_ID like", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotLike(String value) {
            addCriterion("CRT_OPER_ID not like", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdIn(List<String> values) {
            addCriterion("CRT_OPER_ID in", values, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotIn(List<String> values) {
            addCriterion("CRT_OPER_ID not in", values, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdBetween(String value1, String value2) {
            addCriterion("CRT_OPER_ID between", value1, value2, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotBetween(String value1, String value2) {
            addCriterion("CRT_OPER_ID not between", value1, value2, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andUpdDateIsNull() {
            addCriterion("UPD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdDateIsNotNull() {
            addCriterion("UPD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDateEqualTo(String value) {
            addCriterion("UPD_DATE =", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotEqualTo(String value) {
            addCriterion("UPD_DATE <>", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateGreaterThan(String value) {
            addCriterion("UPD_DATE >", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_DATE >=", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLessThan(String value) {
            addCriterion("UPD_DATE <", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLessThanOrEqualTo(String value) {
            addCriterion("UPD_DATE <=", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateLike(String value) {
            addCriterion("UPD_DATE like", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotLike(String value) {
            addCriterion("UPD_DATE not like", value, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateIn(List<String> values) {
            addCriterion("UPD_DATE in", values, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotIn(List<String> values) {
            addCriterion("UPD_DATE not in", values, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateBetween(String value1, String value2) {
            addCriterion("UPD_DATE between", value1, value2, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdDateNotBetween(String value1, String value2) {
            addCriterion("UPD_DATE not between", value1, value2, "updDate");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("UPD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("UPD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(String value) {
            addCriterion("UPD_TIME =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(String value) {
            addCriterion("UPD_TIME <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(String value) {
            addCriterion("UPD_TIME >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_TIME >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(String value) {
            addCriterion("UPD_TIME <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(String value) {
            addCriterion("UPD_TIME <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLike(String value) {
            addCriterion("UPD_TIME like", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotLike(String value) {
            addCriterion("UPD_TIME not like", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<String> values) {
            addCriterion("UPD_TIME in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<String> values) {
            addCriterion("UPD_TIME not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(String value1, String value2) {
            addCriterion("UPD_TIME between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(String value1, String value2) {
            addCriterion("UPD_TIME not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdIsNull() {
            addCriterion("UPD_OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdIsNotNull() {
            addCriterion("UPD_OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdEqualTo(String value) {
            addCriterion("UPD_OPER_ID =", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdNotEqualTo(String value) {
            addCriterion("UPD_OPER_ID <>", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdGreaterThan(String value) {
            addCriterion("UPD_OPER_ID >", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPD_OPER_ID >=", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdLessThan(String value) {
            addCriterion("UPD_OPER_ID <", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdLessThanOrEqualTo(String value) {
            addCriterion("UPD_OPER_ID <=", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdLike(String value) {
            addCriterion("UPD_OPER_ID like", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdNotLike(String value) {
            addCriterion("UPD_OPER_ID not like", value, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdIn(List<String> values) {
            addCriterion("UPD_OPER_ID in", values, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdNotIn(List<String> values) {
            addCriterion("UPD_OPER_ID not in", values, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdBetween(String value1, String value2) {
            addCriterion("UPD_OPER_ID between", value1, value2, "updOperId");
            return (Criteria) this;
        }

        public Criteria andUpdOperIdNotBetween(String value1, String value2) {
            addCriterion("UPD_OPER_ID not between", value1, value2, "updOperId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 27 14:17:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INV_ZZS_CUST
     *
     * @mbggenerated Wed Apr 27 14:17:26 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}