package pfms.repository.model;

import java.util.Date;

public class InvZzsZf extends InvZzsZfKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.TAG1
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String tag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.TAG2
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String tag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.CLBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String clbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date xrrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.SKRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Date skrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.CLCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private Short clcs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.TAG1
     *
     * @return the value of INV_ZZS_ZF.TAG1
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getTag1() {
        return tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.TAG1
     *
     * @param tag1 the value for INV_ZZS_ZF.TAG1
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setTag1(String tag1) {
        this.tag1 = tag1 == null ? null : tag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.TAG2
     *
     * @return the value of INV_ZZS_ZF.TAG2
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getTag2() {
        return tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.TAG2
     *
     * @param tag2 the value for INV_ZZS_ZF.TAG2
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setTag2(String tag2) {
        this.tag2 = tag2 == null ? null : tag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.MSG
     *
     * @return the value of INV_ZZS_ZF.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.MSG
     *
     * @param msg the value for INV_ZZS_ZF.MSG
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.CLBZ
     *
     * @return the value of INV_ZZS_ZF.CLBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getClbz() {
        return clbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.CLBZ
     *
     * @param clbz the value for INV_ZZS_ZF.CLBZ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setClbz(String clbz) {
        this.clbz = clbz == null ? null : clbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.XRRQ
     *
     * @return the value of INV_ZZS_ZF.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getXrrq() {
        return xrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.XRRQ
     *
     * @param xrrq the value for INV_ZZS_ZF.XRRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setXrrq(Date xrrq) {
        this.xrrq = xrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.SKRQ
     *
     * @return the value of INV_ZZS_ZF.SKRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Date getSkrq() {
        return skrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.SKRQ
     *
     * @param skrq the value for INV_ZZS_ZF.SKRQ
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setSkrq(Date skrq) {
        this.skrq = skrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.CLCS
     *
     * @return the value of INV_ZZS_ZF.CLCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public Short getClcs() {
        return clcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.CLCS
     *
     * @param clcs the value for INV_ZZS_ZF.CLCS
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setClcs(Short clcs) {
        this.clcs = clcs;
    }
}