package pfms.repository.model;

public class InvZzsZfKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.INVOICECODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String invoicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INV_ZZS_ZF.TYPE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.INVOICECODE
     *
     * @return the value of INV_ZZS_ZF.INVOICECODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getInvoicecode() {
        return invoicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.INVOICECODE
     *
     * @param invoicecode the value for INV_ZZS_ZF.INVOICECODE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setInvoicecode(String invoicecode) {
        this.invoicecode = invoicecode == null ? null : invoicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INV_ZZS_ZF.TYPE
     *
     * @return the value of INV_ZZS_ZF.TYPE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INV_ZZS_ZF.TYPE
     *
     * @param type the value for INV_ZZS_ZF.TYPE
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}