package skyline.stp.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import skyline.stp.repository.model.StpScheduleJob;
import skyline.stp.repository.model.StpScheduleJobExample;

@Component
public interface StpScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int countByExample(StpScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int deleteByExample(StpScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int insert(StpScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int insertSelective(StpScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    List<StpScheduleJob> selectByExample(StpScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    StpScheduleJob selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") StpScheduleJob record, @Param("example") StpScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int updateByExample(@Param("record") StpScheduleJob record, @Param("example") StpScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int updateByPrimaryKeySelective(StpScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    int updateByPrimaryKey(StpScheduleJob record);
}