package skyline.stp.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import skyline.stp.repository.model.StpScheduleLog;
import skyline.stp.repository.model.StpScheduleLogExample;

@Component
public interface StpScheduleLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    int countByExample(StpScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    int deleteByExample(StpScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    int insert(StpScheduleLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    int insertSelective(StpScheduleLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    List<StpScheduleLog> selectByExample(StpScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") StpScheduleLog record, @Param("example") StpScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    int updateByExample(@Param("record") StpScheduleLog record, @Param("example") StpScheduleLogExample example);
}