package skyline.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.repository.model.Ptmenufavo;
import skyline.repository.model.PtmenufavoExample;

public interface PtmenufavoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int countByExample(PtmenufavoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int deleteByExample(PtmenufavoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insert(Ptmenufavo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insertSelective(Ptmenufavo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    List<Ptmenufavo> selectByExample(PtmenufavoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Ptmenufavo record, @Param("example") PtmenufavoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENUFAVO
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExample(@Param("record") Ptmenufavo record, @Param("example") PtmenufavoExample example);
}