package skyline.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.repository.model.Ptoplog;
import skyline.repository.model.PtoplogExample;

public interface PtoplogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int countByExample(PtoplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int deleteByExample(PtoplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insert(Ptoplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insertSelective(Ptoplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    List<Ptoplog> selectByExample(PtoplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    Ptoplog selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Ptoplog record, @Param("example") PtoplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExample(@Param("record") Ptoplog record, @Param("example") PtoplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByPrimaryKeySelective(Ptoplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByPrimaryKey(Ptoplog record);
}