package skyline.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.repository.model.Ptresource;
import skyline.repository.model.PtresourceExample;

public interface PtresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int countByExample(PtresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int deleteByExample(PtresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insert(Ptresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insertSelective(Ptresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    List<Ptresource> selectByExample(PtresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Ptresource record, @Param("example") PtresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTRESOURCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExample(@Param("record") Ptresource record, @Param("example") PtresourceExample example);
}