package skyline.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.repository.model.Ptsequence;
import skyline.repository.model.PtsequenceExample;

public interface PtsequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int countByExample(PtsequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int deleteByExample(PtsequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int deleteByPrimaryKey(String seqname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insert(Ptsequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int insertSelective(Ptsequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    List<Ptsequence> selectByExample(PtsequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    Ptsequence selectByPrimaryKey(String seqname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Ptsequence record, @Param("example") PtsequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByExample(@Param("record") Ptsequence record, @Param("example") PtsequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByPrimaryKeySelective(Ptsequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTSEQUENCE
     *
     * @mbggenerated Tue Jan 12 13:20:41 CST 2016
     */
    int updateByPrimaryKey(Ptsequence record);
}