package pfms.repository.model.rwkj;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class XwsqZzsItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public XwsqZzsItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXsddmIsNull() {
            addCriterion("XSDDM is null");
            return (Criteria) this;
        }

        public Criteria andXsddmIsNotNull() {
            addCriterion("XSDDM is not null");
            return (Criteria) this;
        }

        public Criteria andXsddmEqualTo(String value) {
            addCriterion("XSDDM =", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmNotEqualTo(String value) {
            addCriterion("XSDDM <>", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmGreaterThan(String value) {
            addCriterion("XSDDM >", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmGreaterThanOrEqualTo(String value) {
            addCriterion("XSDDM >=", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmLessThan(String value) {
            addCriterion("XSDDM <", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmLessThanOrEqualTo(String value) {
            addCriterion("XSDDM <=", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmLike(String value) {
            addCriterion("XSDDM like", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmNotLike(String value) {
            addCriterion("XSDDM not like", value, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmIn(List<String> values) {
            addCriterion("XSDDM in", values, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmNotIn(List<String> values) {
            addCriterion("XSDDM not in", values, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmBetween(String value1, String value2) {
            addCriterion("XSDDM between", value1, value2, "xsddm");
            return (Criteria) this;
        }

        public Criteria andXsddmNotBetween(String value1, String value2) {
            addCriterion("XSDDM not between", value1, value2, "xsddm");
            return (Criteria) this;
        }

        public Criteria andDmgsIsNull() {
            addCriterion("DMGS is null");
            return (Criteria) this;
        }

        public Criteria andDmgsIsNotNull() {
            addCriterion("DMGS is not null");
            return (Criteria) this;
        }

        public Criteria andDmgsEqualTo(String value) {
            addCriterion("DMGS =", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsNotEqualTo(String value) {
            addCriterion("DMGS <>", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsGreaterThan(String value) {
            addCriterion("DMGS >", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsGreaterThanOrEqualTo(String value) {
            addCriterion("DMGS >=", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsLessThan(String value) {
            addCriterion("DMGS <", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsLessThanOrEqualTo(String value) {
            addCriterion("DMGS <=", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsLike(String value) {
            addCriterion("DMGS like", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsNotLike(String value) {
            addCriterion("DMGS not like", value, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsIn(List<String> values) {
            addCriterion("DMGS in", values, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsNotIn(List<String> values) {
            addCriterion("DMGS not in", values, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsBetween(String value1, String value2) {
            addCriterion("DMGS between", value1, value2, "dmgs");
            return (Criteria) this;
        }

        public Criteria andDmgsNotBetween(String value1, String value2) {
            addCriterion("DMGS not between", value1, value2, "dmgs");
            return (Criteria) this;
        }

        public Criteria andMxxhIsNull() {
            addCriterion("MXXH is null");
            return (Criteria) this;
        }

        public Criteria andMxxhIsNotNull() {
            addCriterion("MXXH is not null");
            return (Criteria) this;
        }

        public Criteria andMxxhEqualTo(Short value) {
            addCriterion("MXXH =", value, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhNotEqualTo(Short value) {
            addCriterion("MXXH <>", value, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhGreaterThan(Short value) {
            addCriterion("MXXH >", value, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhGreaterThanOrEqualTo(Short value) {
            addCriterion("MXXH >=", value, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhLessThan(Short value) {
            addCriterion("MXXH <", value, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhLessThanOrEqualTo(Short value) {
            addCriterion("MXXH <=", value, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhIn(List<Short> values) {
            addCriterion("MXXH in", values, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhNotIn(List<Short> values) {
            addCriterion("MXXH not in", values, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhBetween(Short value1, Short value2) {
            addCriterion("MXXH between", value1, value2, "mxxh");
            return (Criteria) this;
        }

        public Criteria andMxxhNotBetween(Short value1, Short value2) {
            addCriterion("MXXH not between", value1, value2, "mxxh");
            return (Criteria) this;
        }

        public Criteria andCpdmIsNull() {
            addCriterion("CPDM is null");
            return (Criteria) this;
        }

        public Criteria andCpdmIsNotNull() {
            addCriterion("CPDM is not null");
            return (Criteria) this;
        }

        public Criteria andCpdmEqualTo(String value) {
            addCriterion("CPDM =", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmNotEqualTo(String value) {
            addCriterion("CPDM <>", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmGreaterThan(String value) {
            addCriterion("CPDM >", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmGreaterThanOrEqualTo(String value) {
            addCriterion("CPDM >=", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmLessThan(String value) {
            addCriterion("CPDM <", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmLessThanOrEqualTo(String value) {
            addCriterion("CPDM <=", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmLike(String value) {
            addCriterion("CPDM like", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmNotLike(String value) {
            addCriterion("CPDM not like", value, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmIn(List<String> values) {
            addCriterion("CPDM in", values, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmNotIn(List<String> values) {
            addCriterion("CPDM not in", values, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmBetween(String value1, String value2) {
            addCriterion("CPDM between", value1, value2, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpdmNotBetween(String value1, String value2) {
            addCriterion("CPDM not between", value1, value2, "cpdm");
            return (Criteria) this;
        }

        public Criteria andCpmcIsNull() {
            addCriterion("CPMC is null");
            return (Criteria) this;
        }

        public Criteria andCpmcIsNotNull() {
            addCriterion("CPMC is not null");
            return (Criteria) this;
        }

        public Criteria andCpmcEqualTo(String value) {
            addCriterion("CPMC =", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcNotEqualTo(String value) {
            addCriterion("CPMC <>", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcGreaterThan(String value) {
            addCriterion("CPMC >", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcGreaterThanOrEqualTo(String value) {
            addCriterion("CPMC >=", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcLessThan(String value) {
            addCriterion("CPMC <", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcLessThanOrEqualTo(String value) {
            addCriterion("CPMC <=", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcLike(String value) {
            addCriterion("CPMC like", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcNotLike(String value) {
            addCriterion("CPMC not like", value, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcIn(List<String> values) {
            addCriterion("CPMC in", values, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcNotIn(List<String> values) {
            addCriterion("CPMC not in", values, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcBetween(String value1, String value2) {
            addCriterion("CPMC between", value1, value2, "cpmc");
            return (Criteria) this;
        }

        public Criteria andCpmcNotBetween(String value1, String value2) {
            addCriterion("CPMC not between", value1, value2, "cpmc");
            return (Criteria) this;
        }

        public Criteria andXhIsNull() {
            addCriterion("XH is null");
            return (Criteria) this;
        }

        public Criteria andXhIsNotNull() {
            addCriterion("XH is not null");
            return (Criteria) this;
        }

        public Criteria andXhEqualTo(String value) {
            addCriterion("XH =", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotEqualTo(String value) {
            addCriterion("XH <>", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThan(String value) {
            addCriterion("XH >", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThanOrEqualTo(String value) {
            addCriterion("XH >=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThan(String value) {
            addCriterion("XH <", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThanOrEqualTo(String value) {
            addCriterion("XH <=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLike(String value) {
            addCriterion("XH like", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotLike(String value) {
            addCriterion("XH not like", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhIn(List<String> values) {
            addCriterion("XH in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotIn(List<String> values) {
            addCriterion("XH not in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhBetween(String value1, String value2) {
            addCriterion("XH between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotBetween(String value1, String value2) {
            addCriterion("XH not between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andCpdwIsNull() {
            addCriterion("CPDW is null");
            return (Criteria) this;
        }

        public Criteria andCpdwIsNotNull() {
            addCriterion("CPDW is not null");
            return (Criteria) this;
        }

        public Criteria andCpdwEqualTo(String value) {
            addCriterion("CPDW =", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwNotEqualTo(String value) {
            addCriterion("CPDW <>", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwGreaterThan(String value) {
            addCriterion("CPDW >", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwGreaterThanOrEqualTo(String value) {
            addCriterion("CPDW >=", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwLessThan(String value) {
            addCriterion("CPDW <", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwLessThanOrEqualTo(String value) {
            addCriterion("CPDW <=", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwLike(String value) {
            addCriterion("CPDW like", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwNotLike(String value) {
            addCriterion("CPDW not like", value, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwIn(List<String> values) {
            addCriterion("CPDW in", values, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwNotIn(List<String> values) {
            addCriterion("CPDW not in", values, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwBetween(String value1, String value2) {
            addCriterion("CPDW between", value1, value2, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpdwNotBetween(String value1, String value2) {
            addCriterion("CPDW not between", value1, value2, "cpdw");
            return (Criteria) this;
        }

        public Criteria andCpslIsNull() {
            addCriterion("CPSL is null");
            return (Criteria) this;
        }

        public Criteria andCpslIsNotNull() {
            addCriterion("CPSL is not null");
            return (Criteria) this;
        }

        public Criteria andCpslEqualTo(BigDecimal value) {
            addCriterion("CPSL =", value, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslNotEqualTo(BigDecimal value) {
            addCriterion("CPSL <>", value, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslGreaterThan(BigDecimal value) {
            addCriterion("CPSL >", value, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CPSL >=", value, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslLessThan(BigDecimal value) {
            addCriterion("CPSL <", value, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CPSL <=", value, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslIn(List<BigDecimal> values) {
            addCriterion("CPSL in", values, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslNotIn(List<BigDecimal> values) {
            addCriterion("CPSL not in", values, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CPSL between", value1, value2, "cpsl");
            return (Criteria) this;
        }

        public Criteria andCpslNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CPSL not between", value1, value2, "cpsl");
            return (Criteria) this;
        }

        public Criteria andHsdjIsNull() {
            addCriterion("HSDJ is null");
            return (Criteria) this;
        }

        public Criteria andHsdjIsNotNull() {
            addCriterion("HSDJ is not null");
            return (Criteria) this;
        }

        public Criteria andHsdjEqualTo(BigDecimal value) {
            addCriterion("HSDJ =", value, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjNotEqualTo(BigDecimal value) {
            addCriterion("HSDJ <>", value, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjGreaterThan(BigDecimal value) {
            addCriterion("HSDJ >", value, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HSDJ >=", value, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjLessThan(BigDecimal value) {
            addCriterion("HSDJ <", value, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HSDJ <=", value, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjIn(List<BigDecimal> values) {
            addCriterion("HSDJ in", values, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjNotIn(List<BigDecimal> values) {
            addCriterion("HSDJ not in", values, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HSDJ between", value1, value2, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsdjNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HSDJ not between", value1, value2, "hsdj");
            return (Criteria) this;
        }

        public Criteria andHsjeIsNull() {
            addCriterion("HSJE is null");
            return (Criteria) this;
        }

        public Criteria andHsjeIsNotNull() {
            addCriterion("HSJE is not null");
            return (Criteria) this;
        }

        public Criteria andHsjeEqualTo(BigDecimal value) {
            addCriterion("HSJE =", value, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeNotEqualTo(BigDecimal value) {
            addCriterion("HSJE <>", value, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeGreaterThan(BigDecimal value) {
            addCriterion("HSJE >", value, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HSJE >=", value, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeLessThan(BigDecimal value) {
            addCriterion("HSJE <", value, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HSJE <=", value, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeIn(List<BigDecimal> values) {
            addCriterion("HSJE in", values, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeNotIn(List<BigDecimal> values) {
            addCriterion("HSJE not in", values, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HSJE between", value1, value2, "hsje");
            return (Criteria) this;
        }

        public Criteria andHsjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HSJE not between", value1, value2, "hsje");
            return (Criteria) this;
        }

        public Criteria andXxdjIsNull() {
            addCriterion("XXDJ is null");
            return (Criteria) this;
        }

        public Criteria andXxdjIsNotNull() {
            addCriterion("XXDJ is not null");
            return (Criteria) this;
        }

        public Criteria andXxdjEqualTo(BigDecimal value) {
            addCriterion("XXDJ =", value, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjNotEqualTo(BigDecimal value) {
            addCriterion("XXDJ <>", value, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjGreaterThan(BigDecimal value) {
            addCriterion("XXDJ >", value, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("XXDJ >=", value, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjLessThan(BigDecimal value) {
            addCriterion("XXDJ <", value, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjLessThanOrEqualTo(BigDecimal value) {
            addCriterion("XXDJ <=", value, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjIn(List<BigDecimal> values) {
            addCriterion("XXDJ in", values, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjNotIn(List<BigDecimal> values) {
            addCriterion("XXDJ not in", values, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XXDJ between", value1, value2, "xxdj");
            return (Criteria) this;
        }

        public Criteria andXxdjNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XXDJ not between", value1, value2, "xxdj");
            return (Criteria) this;
        }

        public Criteria andBhsjeIsNull() {
            addCriterion("BHSJE is null");
            return (Criteria) this;
        }

        public Criteria andBhsjeIsNotNull() {
            addCriterion("BHSJE is not null");
            return (Criteria) this;
        }

        public Criteria andBhsjeEqualTo(BigDecimal value) {
            addCriterion("BHSJE =", value, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeNotEqualTo(BigDecimal value) {
            addCriterion("BHSJE <>", value, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeGreaterThan(BigDecimal value) {
            addCriterion("BHSJE >", value, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BHSJE >=", value, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeLessThan(BigDecimal value) {
            addCriterion("BHSJE <", value, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BHSJE <=", value, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeIn(List<BigDecimal> values) {
            addCriterion("BHSJE in", values, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeNotIn(List<BigDecimal> values) {
            addCriterion("BHSJE not in", values, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BHSJE between", value1, value2, "bhsje");
            return (Criteria) this;
        }

        public Criteria andBhsjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BHSJE not between", value1, value2, "bhsje");
            return (Criteria) this;
        }

        public Criteria andSeIsNull() {
            addCriterion("SE is null");
            return (Criteria) this;
        }

        public Criteria andSeIsNotNull() {
            addCriterion("SE is not null");
            return (Criteria) this;
        }

        public Criteria andSeEqualTo(BigDecimal value) {
            addCriterion("SE =", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeNotEqualTo(BigDecimal value) {
            addCriterion("SE <>", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeGreaterThan(BigDecimal value) {
            addCriterion("SE >", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SE >=", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeLessThan(BigDecimal value) {
            addCriterion("SE <", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SE <=", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeIn(List<BigDecimal> values) {
            addCriterion("SE in", values, "se");
            return (Criteria) this;
        }

        public Criteria andSeNotIn(List<BigDecimal> values) {
            addCriterion("SE not in", values, "se");
            return (Criteria) this;
        }

        public Criteria andSeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SE between", value1, value2, "se");
            return (Criteria) this;
        }

        public Criteria andSeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SE not between", value1, value2, "se");
            return (Criteria) this;
        }

        public Criteria andSlIsNull() {
            addCriterion("SL is null");
            return (Criteria) this;
        }

        public Criteria andSlIsNotNull() {
            addCriterion("SL is not null");
            return (Criteria) this;
        }

        public Criteria andSlEqualTo(BigDecimal value) {
            addCriterion("SL =", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotEqualTo(BigDecimal value) {
            addCriterion("SL <>", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThan(BigDecimal value) {
            addCriterion("SL >", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SL >=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThan(BigDecimal value) {
            addCriterion("SL <", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SL <=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlIn(List<BigDecimal> values) {
            addCriterion("SL in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotIn(List<BigDecimal> values) {
            addCriterion("SL not in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SL between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SL not between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andZbhsjeIsNull() {
            addCriterion("ZBHSJE is null");
            return (Criteria) this;
        }

        public Criteria andZbhsjeIsNotNull() {
            addCriterion("ZBHSJE is not null");
            return (Criteria) this;
        }

        public Criteria andZbhsjeEqualTo(BigDecimal value) {
            addCriterion("ZBHSJE =", value, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeNotEqualTo(BigDecimal value) {
            addCriterion("ZBHSJE <>", value, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeGreaterThan(BigDecimal value) {
            addCriterion("ZBHSJE >", value, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZBHSJE >=", value, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeLessThan(BigDecimal value) {
            addCriterion("ZBHSJE <", value, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZBHSJE <=", value, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeIn(List<BigDecimal> values) {
            addCriterion("ZBHSJE in", values, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeNotIn(List<BigDecimal> values) {
            addCriterion("ZBHSJE not in", values, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZBHSJE between", value1, value2, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZbhsjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZBHSJE not between", value1, value2, "zbhsje");
            return (Criteria) this;
        }

        public Criteria andZseIsNull() {
            addCriterion("ZSE is null");
            return (Criteria) this;
        }

        public Criteria andZseIsNotNull() {
            addCriterion("ZSE is not null");
            return (Criteria) this;
        }

        public Criteria andZseEqualTo(BigDecimal value) {
            addCriterion("ZSE =", value, "zse");
            return (Criteria) this;
        }

        public Criteria andZseNotEqualTo(BigDecimal value) {
            addCriterion("ZSE <>", value, "zse");
            return (Criteria) this;
        }

        public Criteria andZseGreaterThan(BigDecimal value) {
            addCriterion("ZSE >", value, "zse");
            return (Criteria) this;
        }

        public Criteria andZseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZSE >=", value, "zse");
            return (Criteria) this;
        }

        public Criteria andZseLessThan(BigDecimal value) {
            addCriterion("ZSE <", value, "zse");
            return (Criteria) this;
        }

        public Criteria andZseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZSE <=", value, "zse");
            return (Criteria) this;
        }

        public Criteria andZseIn(List<BigDecimal> values) {
            addCriterion("ZSE in", values, "zse");
            return (Criteria) this;
        }

        public Criteria andZseNotIn(List<BigDecimal> values) {
            addCriterion("ZSE not in", values, "zse");
            return (Criteria) this;
        }

        public Criteria andZseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZSE between", value1, value2, "zse");
            return (Criteria) this;
        }

        public Criteria andZseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZSE not between", value1, value2, "zse");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 25 09:11:23 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RWKJ.XWSQ_ZZS_ITEM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}