package pfms.repository.model.rwkj;

public class XwsqZzsHeadKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_HEAD.XSDDM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String xsddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_HEAD.DMGS
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String dmgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_HEAD.XSDDM
     *
     * @return the value of RWKJ.XWSQ_ZZS_HEAD.XSDDM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getXsddm() {
        return xsddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_HEAD.XSDDM
     *
     * @param xsddm the value for RWKJ.XWSQ_ZZS_HEAD.XSDDM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setXsddm(String xsddm) {
        this.xsddm = xsddm == null ? null : xsddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_HEAD.DMGS
     *
     * @return the value of RWKJ.XWSQ_ZZS_HEAD.DMGS
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getDmgs() {
        return dmgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_HEAD.DMGS
     *
     * @param dmgs the value for RWKJ.XWSQ_ZZS_HEAD.DMGS
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setDmgs(String dmgs) {
        this.dmgs = dmgs == null ? null : dmgs.trim();
    }
}