package pfms.repository.model.rwkj;

public class XwsqZzsZfKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_ZF.INVOICECODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String invoicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_ZF.TYPE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_ZF.INVOICECODE
     *
     * @return the value of RWKJ.XWSQ_ZZS_ZF.INVOICECODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getInvoicecode() {
        return invoicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_ZF.INVOICECODE
     *
     * @param invoicecode the value for RWKJ.XWSQ_ZZS_ZF.INVOICECODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setInvoicecode(String invoicecode) {
        this.invoicecode = invoicecode == null ? null : invoicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_ZF.TYPE
     *
     * @return the value of RWKJ.XWSQ_ZZS_ZF.TYPE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_ZF.TYPE
     *
     * @param type the value for RWKJ.XWSQ_ZZS_ZF.TYPE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}