package pfms.repository.model.rwkj;

import java.math.BigDecimal;
import java.util.Date;

public class XwsqZzsKphx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.XSDDM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String xsddm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.FLAG
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.INVOICECODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String invoicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.KPRQ
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String kprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.FISCALCODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String fiscalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.NOTAXAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private BigDecimal notaxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.TAXAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private BigDecimal taxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.TOTALAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private BigDecimal totalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.DRAWER
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String drawer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.VIEWURL
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String viewurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.TAG1
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String tag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.TAG2
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String tag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.MSG
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.DMGS
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private String dmgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RWKJ.XWSQ_ZZS_KPHX.XRRQ
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    private Date xrrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.XSDDM
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.XSDDM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getXsddm() {
        return xsddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.XSDDM
     *
     * @param xsddm the value for RWKJ.XWSQ_ZZS_KPHX.XSDDM
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setXsddm(String xsddm) {
        this.xsddm = xsddm == null ? null : xsddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.FLAG
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.FLAG
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.FLAG
     *
     * @param flag the value for RWKJ.XWSQ_ZZS_KPHX.FLAG
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.INVOICECODE
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.INVOICECODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getInvoicecode() {
        return invoicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.INVOICECODE
     *
     * @param invoicecode the value for RWKJ.XWSQ_ZZS_KPHX.INVOICECODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setInvoicecode(String invoicecode) {
        this.invoicecode = invoicecode == null ? null : invoicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.KPRQ
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.KPRQ
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getKprq() {
        return kprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.KPRQ
     *
     * @param kprq the value for RWKJ.XWSQ_ZZS_KPHX.KPRQ
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setKprq(String kprq) {
        this.kprq = kprq == null ? null : kprq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.FISCALCODE
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.FISCALCODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getFiscalcode() {
        return fiscalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.FISCALCODE
     *
     * @param fiscalcode the value for RWKJ.XWSQ_ZZS_KPHX.FISCALCODE
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setFiscalcode(String fiscalcode) {
        this.fiscalcode = fiscalcode == null ? null : fiscalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.NOTAXAMOUNT
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.NOTAXAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public BigDecimal getNotaxamount() {
        return notaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.NOTAXAMOUNT
     *
     * @param notaxamount the value for RWKJ.XWSQ_ZZS_KPHX.NOTAXAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setNotaxamount(BigDecimal notaxamount) {
        this.notaxamount = notaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.TAXAMOUNT
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.TAXAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public BigDecimal getTaxamount() {
        return taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.TAXAMOUNT
     *
     * @param taxamount the value for RWKJ.XWSQ_ZZS_KPHX.TAXAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setTaxamount(BigDecimal taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.TOTALAMOUNT
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.TOTALAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public BigDecimal getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.TOTALAMOUNT
     *
     * @param totalamount the value for RWKJ.XWSQ_ZZS_KPHX.TOTALAMOUNT
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.DRAWER
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.DRAWER
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getDrawer() {
        return drawer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.DRAWER
     *
     * @param drawer the value for RWKJ.XWSQ_ZZS_KPHX.DRAWER
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setDrawer(String drawer) {
        this.drawer = drawer == null ? null : drawer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.VIEWURL
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.VIEWURL
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getViewurl() {
        return viewurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.VIEWURL
     *
     * @param viewurl the value for RWKJ.XWSQ_ZZS_KPHX.VIEWURL
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setViewurl(String viewurl) {
        this.viewurl = viewurl == null ? null : viewurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.TAG1
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.TAG1
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getTag1() {
        return tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.TAG1
     *
     * @param tag1 the value for RWKJ.XWSQ_ZZS_KPHX.TAG1
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setTag1(String tag1) {
        this.tag1 = tag1 == null ? null : tag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.TAG2
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.TAG2
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getTag2() {
        return tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.TAG2
     *
     * @param tag2 the value for RWKJ.XWSQ_ZZS_KPHX.TAG2
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setTag2(String tag2) {
        this.tag2 = tag2 == null ? null : tag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.MSG
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.MSG
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.MSG
     *
     * @param msg the value for RWKJ.XWSQ_ZZS_KPHX.MSG
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.DMGS
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.DMGS
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public String getDmgs() {
        return dmgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.DMGS
     *
     * @param dmgs the value for RWKJ.XWSQ_ZZS_KPHX.DMGS
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setDmgs(String dmgs) {
        this.dmgs = dmgs == null ? null : dmgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RWKJ.XWSQ_ZZS_KPHX.XRRQ
     *
     * @return the value of RWKJ.XWSQ_ZZS_KPHX.XRRQ
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public Date getXrrq() {
        return xrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RWKJ.XWSQ_ZZS_KPHX.XRRQ
     *
     * @param xrrq the value for RWKJ.XWSQ_ZZS_KPHX.XRRQ
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    public void setXrrq(Date xrrq) {
        this.xrrq = xrrq;
    }
}