package pfms.repository.dao.rwkj;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pfms.repository.model.rwkj.XwsqZzsHead;
import pfms.repository.model.rwkj.XwsqZzsHeadExample;
import pfms.repository.model.rwkj.XwsqZzsHeadKey;

public interface XwsqZzsHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int countByExample(XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int deleteByExample(XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int deleteByPrimaryKey(XwsqZzsHeadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int insert(XwsqZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int insertSelective(XwsqZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    List<XwsqZzsHead> selectByExampleWithBLOBs(XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    List<XwsqZzsHead> selectByExample(XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    XwsqZzsHead selectByPrimaryKey(XwsqZzsHeadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") XwsqZzsHead record, @Param("example") XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") XwsqZzsHead record, @Param("example") XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int updateByExample(@Param("record") XwsqZzsHead record, @Param("example") XwsqZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int updateByPrimaryKeySelective(XwsqZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(XwsqZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_HEAD
     *
     * @mbggenerated Wed May 18 16:56:22 CST 2016
     */
    int updateByPrimaryKey(XwsqZzsHead record);
}