package pfms.repository.dao.rwkj;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pfms.repository.model.rwkj.XwsqZzsKphx;
import pfms.repository.model.rwkj.XwsqZzsKphxExample;

public interface XwsqZzsKphxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    int countByExample(XwsqZzsKphxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    int deleteByExample(XwsqZzsKphxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    int insert(XwsqZzsKphx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    int insertSelective(XwsqZzsKphx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    List<XwsqZzsKphx> selectByExample(XwsqZzsKphxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") XwsqZzsKphx record, @Param("example") XwsqZzsKphxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RWKJ.XWSQ_ZZS_KPHX
     *
     * @mbggenerated Mon Apr 25 09:11:23 CST 2016
     */
    int updateByExample(@Param("record") XwsqZzsKphx record, @Param("example") XwsqZzsKphxExample example);
}