package pfms.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pfms.repository.model.InvZzsHead;
import pfms.repository.model.InvZzsHeadExample;
import pfms.repository.model.InvZzsHeadKey;

public interface InvZzsHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int countByExample(InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int deleteByExample(InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int deleteByPrimaryKey(InvZzsHeadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int insert(InvZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int insertSelective(InvZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    List<InvZzsHead> selectByExampleWithBLOBs(InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    List<InvZzsHead> selectByExample(InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    InvZzsHead selectByPrimaryKey(InvZzsHeadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") InvZzsHead record, @Param("example") InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") InvZzsHead record, @Param("example") InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int updateByExample(@Param("record") InvZzsHead record, @Param("example") InvZzsHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int updateByPrimaryKeySelective(InvZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(InvZzsHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_HEAD
     *
     * @mbggenerated Sun Apr 24 16:20:34 CST 2016
     */
    int updateByPrimaryKey(InvZzsHead record);
}