package pfms.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pfms.repository.model.InvZzsSrc;
import pfms.repository.model.InvZzsSrcExample;
import pfms.repository.model.InvZzsSrcKey;

public interface InvZzsSrcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int countByExample(InvZzsSrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int deleteByExample(InvZzsSrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int deleteByPrimaryKey(InvZzsSrcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int insert(InvZzsSrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int insertSelective(InvZzsSrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    List<InvZzsSrc> selectByExample(InvZzsSrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    InvZzsSrc selectByPrimaryKey(InvZzsSrcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") InvZzsSrc record, @Param("example") InvZzsSrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int updateByExample(@Param("record") InvZzsSrc record, @Param("example") InvZzsSrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int updateByPrimaryKeySelective(InvZzsSrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SRC
     *
     * @mbggenerated Fri May 13 07:07:47 CST 2016
     */
    int updateByPrimaryKey(InvZzsSrc record);
}