package pfms.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pfms.repository.model.InvZzsSyncFailExample;
import pfms.repository.model.InvZzsSyncFailKey;

public interface InvZzsSyncFailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int countByExample(InvZzsSyncFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int deleteByExample(InvZzsSyncFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int deleteByPrimaryKey(InvZzsSyncFailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int insert(InvZzsSyncFailKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int insertSelective(InvZzsSyncFailKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    List<InvZzsSyncFailKey> selectByExample(InvZzsSyncFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") InvZzsSyncFailKey record, @Param("example") InvZzsSyncFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INV_ZZS_SYNC_FAIL
     *
     * @mbggenerated Thu Apr 28 07:35:24 CST 2016
     */
    int updateByExample(@Param("record") InvZzsSyncFailKey record, @Param("example") InvZzsSyncFailExample example);
}