package skyline.stp.repository.model;

import java.util.ArrayList;
import java.util.List;

public class StpScheduleJobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public StpScheduleJobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("JOB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("JOB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("JOB_NAME =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("JOB_NAME <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("JOB_NAME >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_NAME >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("JOB_NAME <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("JOB_NAME <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("JOB_NAME like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("JOB_NAME not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("JOB_NAME in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("JOB_NAME not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("JOB_NAME between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("JOB_NAME not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNull() {
            addCriterion("JOB_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNotNull() {
            addCriterion("JOB_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andJobGroupEqualTo(String value) {
            addCriterion("JOB_GROUP =", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotEqualTo(String value) {
            addCriterion("JOB_GROUP <>", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThan(String value) {
            addCriterion("JOB_GROUP >", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP >=", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThan(String value) {
            addCriterion("JOB_GROUP <", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP <=", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLike(String value) {
            addCriterion("JOB_GROUP like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotLike(String value) {
            addCriterion("JOB_GROUP not like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupIn(List<String> values) {
            addCriterion("JOB_GROUP in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotIn(List<String> values) {
            addCriterion("JOB_GROUP not in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupBetween(String value1, String value2) {
            addCriterion("JOB_GROUP between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotBetween(String value1, String value2) {
            addCriterion("JOB_GROUP not between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobTriggerIsNull() {
            addCriterion("JOB_TRIGGER is null");
            return (Criteria) this;
        }

        public Criteria andJobTriggerIsNotNull() {
            addCriterion("JOB_TRIGGER is not null");
            return (Criteria) this;
        }

        public Criteria andJobTriggerEqualTo(String value) {
            addCriterion("JOB_TRIGGER =", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotEqualTo(String value) {
            addCriterion("JOB_TRIGGER <>", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerGreaterThan(String value) {
            addCriterion("JOB_TRIGGER >", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_TRIGGER >=", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerLessThan(String value) {
            addCriterion("JOB_TRIGGER <", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerLessThanOrEqualTo(String value) {
            addCriterion("JOB_TRIGGER <=", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerLike(String value) {
            addCriterion("JOB_TRIGGER like", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotLike(String value) {
            addCriterion("JOB_TRIGGER not like", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerIn(List<String> values) {
            addCriterion("JOB_TRIGGER in", values, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotIn(List<String> values) {
            addCriterion("JOB_TRIGGER not in", values, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerBetween(String value1, String value2) {
            addCriterion("JOB_TRIGGER between", value1, value2, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotBetween(String value1, String value2) {
            addCriterion("JOB_TRIGGER not between", value1, value2, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNull() {
            addCriterion("JOB_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNotNull() {
            addCriterion("JOB_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andJobStatusEqualTo(String value) {
            addCriterion("JOB_STATUS =", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotEqualTo(String value) {
            addCriterion("JOB_STATUS <>", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThan(String value) {
            addCriterion("JOB_STATUS >", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_STATUS >=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThan(String value) {
            addCriterion("JOB_STATUS <", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThanOrEqualTo(String value) {
            addCriterion("JOB_STATUS <=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLike(String value) {
            addCriterion("JOB_STATUS like", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotLike(String value) {
            addCriterion("JOB_STATUS not like", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusIn(List<String> values) {
            addCriterion("JOB_STATUS in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotIn(List<String> values) {
            addCriterion("JOB_STATUS not in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusBetween(String value1, String value2) {
            addCriterion("JOB_STATUS between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotBetween(String value1, String value2) {
            addCriterion("JOB_STATUS not between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobActionIsNull() {
            addCriterion("JOB_ACTION is null");
            return (Criteria) this;
        }

        public Criteria andJobActionIsNotNull() {
            addCriterion("JOB_ACTION is not null");
            return (Criteria) this;
        }

        public Criteria andJobActionEqualTo(String value) {
            addCriterion("JOB_ACTION =", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionNotEqualTo(String value) {
            addCriterion("JOB_ACTION <>", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionGreaterThan(String value) {
            addCriterion("JOB_ACTION >", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_ACTION >=", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionLessThan(String value) {
            addCriterion("JOB_ACTION <", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionLessThanOrEqualTo(String value) {
            addCriterion("JOB_ACTION <=", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionLike(String value) {
            addCriterion("JOB_ACTION like", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionNotLike(String value) {
            addCriterion("JOB_ACTION not like", value, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionIn(List<String> values) {
            addCriterion("JOB_ACTION in", values, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionNotIn(List<String> values) {
            addCriterion("JOB_ACTION not in", values, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionBetween(String value1, String value2) {
            addCriterion("JOB_ACTION between", value1, value2, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobActionNotBetween(String value1, String value2) {
            addCriterion("JOB_ACTION not between", value1, value2, "jobAction");
            return (Criteria) this;
        }

        public Criteria andJobMethodIsNull() {
            addCriterion("JOB_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andJobMethodIsNotNull() {
            addCriterion("JOB_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andJobMethodEqualTo(String value) {
            addCriterion("JOB_METHOD =", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodNotEqualTo(String value) {
            addCriterion("JOB_METHOD <>", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodGreaterThan(String value) {
            addCriterion("JOB_METHOD >", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_METHOD >=", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodLessThan(String value) {
            addCriterion("JOB_METHOD <", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodLessThanOrEqualTo(String value) {
            addCriterion("JOB_METHOD <=", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodLike(String value) {
            addCriterion("JOB_METHOD like", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodNotLike(String value) {
            addCriterion("JOB_METHOD not like", value, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodIn(List<String> values) {
            addCriterion("JOB_METHOD in", values, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodNotIn(List<String> values) {
            addCriterion("JOB_METHOD not in", values, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodBetween(String value1, String value2) {
            addCriterion("JOB_METHOD between", value1, value2, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobMethodNotBetween(String value1, String value2) {
            addCriterion("JOB_METHOD not between", value1, value2, "jobMethod");
            return (Criteria) this;
        }

        public Criteria andJobParamIsNull() {
            addCriterion("JOB_PARAM is null");
            return (Criteria) this;
        }

        public Criteria andJobParamIsNotNull() {
            addCriterion("JOB_PARAM is not null");
            return (Criteria) this;
        }

        public Criteria andJobParamEqualTo(String value) {
            addCriterion("JOB_PARAM =", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotEqualTo(String value) {
            addCriterion("JOB_PARAM <>", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamGreaterThan(String value) {
            addCriterion("JOB_PARAM >", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_PARAM >=", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamLessThan(String value) {
            addCriterion("JOB_PARAM <", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamLessThanOrEqualTo(String value) {
            addCriterion("JOB_PARAM <=", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamLike(String value) {
            addCriterion("JOB_PARAM like", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotLike(String value) {
            addCriterion("JOB_PARAM not like", value, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamIn(List<String> values) {
            addCriterion("JOB_PARAM in", values, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotIn(List<String> values) {
            addCriterion("JOB_PARAM not in", values, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamBetween(String value1, String value2) {
            addCriterion("JOB_PARAM between", value1, value2, "jobParam");
            return (Criteria) this;
        }

        public Criteria andJobParamNotBetween(String value1, String value2) {
            addCriterion("JOB_PARAM not between", value1, value2, "jobParam");
            return (Criteria) this;
        }

        public Criteria andSpringIdIsNull() {
            addCriterion("SPRING_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpringIdIsNotNull() {
            addCriterion("SPRING_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpringIdEqualTo(String value) {
            addCriterion("SPRING_ID =", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotEqualTo(String value) {
            addCriterion("SPRING_ID <>", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdGreaterThan(String value) {
            addCriterion("SPRING_ID >", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdGreaterThanOrEqualTo(String value) {
            addCriterion("SPRING_ID >=", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLessThan(String value) {
            addCriterion("SPRING_ID <", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLessThanOrEqualTo(String value) {
            addCriterion("SPRING_ID <=", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLike(String value) {
            addCriterion("SPRING_ID like", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotLike(String value) {
            addCriterion("SPRING_ID not like", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdIn(List<String> values) {
            addCriterion("SPRING_ID in", values, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotIn(List<String> values) {
            addCriterion("SPRING_ID not in", values, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdBetween(String value1, String value2) {
            addCriterion("SPRING_ID between", value1, value2, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotBetween(String value1, String value2) {
            addCriterion("SPRING_ID not between", value1, value2, "springId");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIsNull() {
            addCriterion("CRON_EXPRESSION is null");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIsNotNull() {
            addCriterion("CRON_EXPRESSION is not null");
            return (Criteria) this;
        }

        public Criteria andCronExpressionEqualTo(String value) {
            addCriterion("CRON_EXPRESSION =", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotEqualTo(String value) {
            addCriterion("CRON_EXPRESSION <>", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionGreaterThan(String value) {
            addCriterion("CRON_EXPRESSION >", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("CRON_EXPRESSION >=", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLessThan(String value) {
            addCriterion("CRON_EXPRESSION <", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLessThanOrEqualTo(String value) {
            addCriterion("CRON_EXPRESSION <=", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLike(String value) {
            addCriterion("CRON_EXPRESSION like", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotLike(String value) {
            addCriterion("CRON_EXPRESSION not like", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIn(List<String> values) {
            addCriterion("CRON_EXPRESSION in", values, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotIn(List<String> values) {
            addCriterion("CRON_EXPRESSION not in", values, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionBetween(String value1, String value2) {
            addCriterion("CRON_EXPRESSION between", value1, value2, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotBetween(String value1, String value2) {
            addCriterion("CRON_EXPRESSION not between", value1, value2, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andIsSyncIsNull() {
            addCriterion("IS_SYNC is null");
            return (Criteria) this;
        }

        public Criteria andIsSyncIsNotNull() {
            addCriterion("IS_SYNC is not null");
            return (Criteria) this;
        }

        public Criteria andIsSyncEqualTo(String value) {
            addCriterion("IS_SYNC =", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotEqualTo(String value) {
            addCriterion("IS_SYNC <>", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncGreaterThan(String value) {
            addCriterion("IS_SYNC >", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncGreaterThanOrEqualTo(String value) {
            addCriterion("IS_SYNC >=", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLessThan(String value) {
            addCriterion("IS_SYNC <", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLessThanOrEqualTo(String value) {
            addCriterion("IS_SYNC <=", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLike(String value) {
            addCriterion("IS_SYNC like", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotLike(String value) {
            addCriterion("IS_SYNC not like", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncIn(List<String> values) {
            addCriterion("IS_SYNC in", values, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotIn(List<String> values) {
            addCriterion("IS_SYNC not in", values, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncBetween(String value1, String value2) {
            addCriterion("IS_SYNC between", value1, value2, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotBetween(String value1, String value2) {
            addCriterion("IS_SYNC not between", value1, value2, "isSync");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedflagIsNull() {
            addCriterion("DELETEDFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeletedflagIsNotNull() {
            addCriterion("DELETEDFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedflagEqualTo(String value) {
            addCriterion("DELETEDFLAG =", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotEqualTo(String value) {
            addCriterion("DELETEDFLAG <>", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagGreaterThan(String value) {
            addCriterion("DELETEDFLAG >", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETEDFLAG >=", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagLessThan(String value) {
            addCriterion("DELETEDFLAG <", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagLessThanOrEqualTo(String value) {
            addCriterion("DELETEDFLAG <=", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagLike(String value) {
            addCriterion("DELETEDFLAG like", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotLike(String value) {
            addCriterion("DELETEDFLAG not like", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagIn(List<String> values) {
            addCriterion("DELETEDFLAG in", values, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotIn(List<String> values) {
            addCriterion("DELETEDFLAG not in", values, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagBetween(String value1, String value2) {
            addCriterion("DELETEDFLAG between", value1, value2, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotBetween(String value1, String value2) {
            addCriterion("DELETEDFLAG not between", value1, value2, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Long value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Long value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Long value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Long value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Long value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Long value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Long> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Long> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Long value1, Long value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Long value1, Long value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIsNull() {
            addCriterion("SCHEDULE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIsNotNull() {
            addCriterion("SCHEDULE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE =", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE <>", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeGreaterThan(String value) {
            addCriterion("SCHEDULE_TYPE >", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE >=", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLessThan(String value) {
            addCriterion("SCHEDULE_TYPE <", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_TYPE <=", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeLike(String value) {
            addCriterion("SCHEDULE_TYPE like", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotLike(String value) {
            addCriterion("SCHEDULE_TYPE not like", value, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeIn(List<String> values) {
            addCriterion("SCHEDULE_TYPE in", values, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotIn(List<String> values) {
            addCriterion("SCHEDULE_TYPE not in", values, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeBetween(String value1, String value2) {
            addCriterion("SCHEDULE_TYPE between", value1, value2, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andScheduleTypeNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_TYPE not between", value1, value2, "scheduleType");
            return (Criteria) this;
        }

        public Criteria andSucessNumIsNull() {
            addCriterion("SUCESS_NUM is null");
            return (Criteria) this;
        }

        public Criteria andSucessNumIsNotNull() {
            addCriterion("SUCESS_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andSucessNumEqualTo(Long value) {
            addCriterion("SUCESS_NUM =", value, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumNotEqualTo(Long value) {
            addCriterion("SUCESS_NUM <>", value, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumGreaterThan(Long value) {
            addCriterion("SUCESS_NUM >", value, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumGreaterThanOrEqualTo(Long value) {
            addCriterion("SUCESS_NUM >=", value, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumLessThan(Long value) {
            addCriterion("SUCESS_NUM <", value, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumLessThanOrEqualTo(Long value) {
            addCriterion("SUCESS_NUM <=", value, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumIn(List<Long> values) {
            addCriterion("SUCESS_NUM in", values, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumNotIn(List<Long> values) {
            addCriterion("SUCESS_NUM not in", values, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumBetween(Long value1, Long value2) {
            addCriterion("SUCESS_NUM between", value1, value2, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andSucessNumNotBetween(Long value1, Long value2) {
            addCriterion("SUCESS_NUM not between", value1, value2, "sucessNum");
            return (Criteria) this;
        }

        public Criteria andFailNumIsNull() {
            addCriterion("FAIL_NUM is null");
            return (Criteria) this;
        }

        public Criteria andFailNumIsNotNull() {
            addCriterion("FAIL_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andFailNumEqualTo(Long value) {
            addCriterion("FAIL_NUM =", value, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumNotEqualTo(Long value) {
            addCriterion("FAIL_NUM <>", value, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumGreaterThan(Long value) {
            addCriterion("FAIL_NUM >", value, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumGreaterThanOrEqualTo(Long value) {
            addCriterion("FAIL_NUM >=", value, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumLessThan(Long value) {
            addCriterion("FAIL_NUM <", value, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumLessThanOrEqualTo(Long value) {
            addCriterion("FAIL_NUM <=", value, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumIn(List<Long> values) {
            addCriterion("FAIL_NUM in", values, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumNotIn(List<Long> values) {
            addCriterion("FAIL_NUM not in", values, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumBetween(Long value1, Long value2) {
            addCriterion("FAIL_NUM between", value1, value2, "failNum");
            return (Criteria) this;
        }

        public Criteria andFailNumNotBetween(Long value1, Long value2) {
            addCriterion("FAIL_NUM not between", value1, value2, "failNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 27 14:58:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STP_SCHEDULE_JOB
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}