package skyline.stp.repository.model;

import java.util.ArrayList;
import java.util.List;

public class StpScheduleLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public StpScheduleLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andTablenameIsNull() {
            addCriterion("TABLENAME is null");
            return (Criteria) this;
        }

        public Criteria andTablenameIsNotNull() {
            addCriterion("TABLENAME is not null");
            return (Criteria) this;
        }

        public Criteria andTablenameEqualTo(String value) {
            addCriterion("TABLENAME =", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotEqualTo(String value) {
            addCriterion("TABLENAME <>", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameGreaterThan(String value) {
            addCriterion("TABLENAME >", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLENAME >=", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLessThan(String value) {
            addCriterion("TABLENAME <", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLessThanOrEqualTo(String value) {
            addCriterion("TABLENAME <=", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLike(String value) {
            addCriterion("TABLENAME like", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotLike(String value) {
            addCriterion("TABLENAME not like", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameIn(List<String> values) {
            addCriterion("TABLENAME in", values, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotIn(List<String> values) {
            addCriterion("TABLENAME not in", values, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameBetween(String value1, String value2) {
            addCriterion("TABLENAME between", value1, value2, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotBetween(String value1, String value2) {
            addCriterion("TABLENAME not between", value1, value2, "tablename");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andRowpkidIsNull() {
            addCriterion("ROWPKID is null");
            return (Criteria) this;
        }

        public Criteria andRowpkidIsNotNull() {
            addCriterion("ROWPKID is not null");
            return (Criteria) this;
        }

        public Criteria andRowpkidEqualTo(String value) {
            addCriterion("ROWPKID =", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidNotEqualTo(String value) {
            addCriterion("ROWPKID <>", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidGreaterThan(String value) {
            addCriterion("ROWPKID >", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidGreaterThanOrEqualTo(String value) {
            addCriterion("ROWPKID >=", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidLessThan(String value) {
            addCriterion("ROWPKID <", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidLessThanOrEqualTo(String value) {
            addCriterion("ROWPKID <=", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidLike(String value) {
            addCriterion("ROWPKID like", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidNotLike(String value) {
            addCriterion("ROWPKID not like", value, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidIn(List<String> values) {
            addCriterion("ROWPKID in", values, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidNotIn(List<String> values) {
            addCriterion("ROWPKID not in", values, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidBetween(String value1, String value2) {
            addCriterion("ROWPKID between", value1, value2, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andRowpkidNotBetween(String value1, String value2) {
            addCriterion("ROWPKID not between", value1, value2, "rowpkid");
            return (Criteria) this;
        }

        public Criteria andJobcodeIsNull() {
            addCriterion("JOBCODE is null");
            return (Criteria) this;
        }

        public Criteria andJobcodeIsNotNull() {
            addCriterion("JOBCODE is not null");
            return (Criteria) this;
        }

        public Criteria andJobcodeEqualTo(String value) {
            addCriterion("JOBCODE =", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeNotEqualTo(String value) {
            addCriterion("JOBCODE <>", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeGreaterThan(String value) {
            addCriterion("JOBCODE >", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeGreaterThanOrEqualTo(String value) {
            addCriterion("JOBCODE >=", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeLessThan(String value) {
            addCriterion("JOBCODE <", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeLessThanOrEqualTo(String value) {
            addCriterion("JOBCODE <=", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeLike(String value) {
            addCriterion("JOBCODE like", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeNotLike(String value) {
            addCriterion("JOBCODE not like", value, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeIn(List<String> values) {
            addCriterion("JOBCODE in", values, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeNotIn(List<String> values) {
            addCriterion("JOBCODE not in", values, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeBetween(String value1, String value2) {
            addCriterion("JOBCODE between", value1, value2, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobcodeNotBetween(String value1, String value2) {
            addCriterion("JOBCODE not between", value1, value2, "jobcode");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNull() {
            addCriterion("JOBNAME is null");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNotNull() {
            addCriterion("JOBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobnameEqualTo(String value) {
            addCriterion("JOBNAME =", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotEqualTo(String value) {
            addCriterion("JOBNAME <>", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThan(String value) {
            addCriterion("JOBNAME >", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThanOrEqualTo(String value) {
            addCriterion("JOBNAME >=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThan(String value) {
            addCriterion("JOBNAME <", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThanOrEqualTo(String value) {
            addCriterion("JOBNAME <=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLike(String value) {
            addCriterion("JOBNAME like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotLike(String value) {
            addCriterion("JOBNAME not like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameIn(List<String> values) {
            addCriterion("JOBNAME in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotIn(List<String> values) {
            addCriterion("JOBNAME not in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameBetween(String value1, String value2) {
            addCriterion("JOBNAME between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotBetween(String value1, String value2) {
            addCriterion("JOBNAME not between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobgroupIsNull() {
            addCriterion("JOBGROUP is null");
            return (Criteria) this;
        }

        public Criteria andJobgroupIsNotNull() {
            addCriterion("JOBGROUP is not null");
            return (Criteria) this;
        }

        public Criteria andJobgroupEqualTo(String value) {
            addCriterion("JOBGROUP =", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotEqualTo(String value) {
            addCriterion("JOBGROUP <>", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupGreaterThan(String value) {
            addCriterion("JOBGROUP >", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupGreaterThanOrEqualTo(String value) {
            addCriterion("JOBGROUP >=", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupLessThan(String value) {
            addCriterion("JOBGROUP <", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupLessThanOrEqualTo(String value) {
            addCriterion("JOBGROUP <=", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupLike(String value) {
            addCriterion("JOBGROUP like", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotLike(String value) {
            addCriterion("JOBGROUP not like", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupIn(List<String> values) {
            addCriterion("JOBGROUP in", values, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotIn(List<String> values) {
            addCriterion("JOBGROUP not in", values, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupBetween(String value1, String value2) {
            addCriterion("JOBGROUP between", value1, value2, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotBetween(String value1, String value2) {
            addCriterion("JOBGROUP not between", value1, value2, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobdescIsNull() {
            addCriterion("JOBDESC is null");
            return (Criteria) this;
        }

        public Criteria andJobdescIsNotNull() {
            addCriterion("JOBDESC is not null");
            return (Criteria) this;
        }

        public Criteria andJobdescEqualTo(String value) {
            addCriterion("JOBDESC =", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescNotEqualTo(String value) {
            addCriterion("JOBDESC <>", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescGreaterThan(String value) {
            addCriterion("JOBDESC >", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescGreaterThanOrEqualTo(String value) {
            addCriterion("JOBDESC >=", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescLessThan(String value) {
            addCriterion("JOBDESC <", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescLessThanOrEqualTo(String value) {
            addCriterion("JOBDESC <=", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescLike(String value) {
            addCriterion("JOBDESC like", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescNotLike(String value) {
            addCriterion("JOBDESC not like", value, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescIn(List<String> values) {
            addCriterion("JOBDESC in", values, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescNotIn(List<String> values) {
            addCriterion("JOBDESC not in", values, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescBetween(String value1, String value2) {
            addCriterion("JOBDESC between", value1, value2, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobdescNotBetween(String value1, String value2) {
            addCriterion("JOBDESC not between", value1, value2, "jobdesc");
            return (Criteria) this;
        }

        public Criteria andJobtimeIsNull() {
            addCriterion("JOBTIME is null");
            return (Criteria) this;
        }

        public Criteria andJobtimeIsNotNull() {
            addCriterion("JOBTIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobtimeEqualTo(String value) {
            addCriterion("JOBTIME =", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeNotEqualTo(String value) {
            addCriterion("JOBTIME <>", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeGreaterThan(String value) {
            addCriterion("JOBTIME >", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeGreaterThanOrEqualTo(String value) {
            addCriterion("JOBTIME >=", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeLessThan(String value) {
            addCriterion("JOBTIME <", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeLessThanOrEqualTo(String value) {
            addCriterion("JOBTIME <=", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeLike(String value) {
            addCriterion("JOBTIME like", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeNotLike(String value) {
            addCriterion("JOBTIME not like", value, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeIn(List<String> values) {
            addCriterion("JOBTIME in", values, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeNotIn(List<String> values) {
            addCriterion("JOBTIME not in", values, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeBetween(String value1, String value2) {
            addCriterion("JOBTIME between", value1, value2, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobtimeNotBetween(String value1, String value2) {
            addCriterion("JOBTIME not between", value1, value2, "jobtime");
            return (Criteria) this;
        }

        public Criteria andJobuseridIsNull() {
            addCriterion("JOBUSERID is null");
            return (Criteria) this;
        }

        public Criteria andJobuseridIsNotNull() {
            addCriterion("JOBUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andJobuseridEqualTo(String value) {
            addCriterion("JOBUSERID =", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridNotEqualTo(String value) {
            addCriterion("JOBUSERID <>", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridGreaterThan(String value) {
            addCriterion("JOBUSERID >", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridGreaterThanOrEqualTo(String value) {
            addCriterion("JOBUSERID >=", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridLessThan(String value) {
            addCriterion("JOBUSERID <", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridLessThanOrEqualTo(String value) {
            addCriterion("JOBUSERID <=", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridLike(String value) {
            addCriterion("JOBUSERID like", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridNotLike(String value) {
            addCriterion("JOBUSERID not like", value, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridIn(List<String> values) {
            addCriterion("JOBUSERID in", values, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridNotIn(List<String> values) {
            addCriterion("JOBUSERID not in", values, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridBetween(String value1, String value2) {
            addCriterion("JOBUSERID between", value1, value2, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobuseridNotBetween(String value1, String value2) {
            addCriterion("JOBUSERID not between", value1, value2, "jobuserid");
            return (Criteria) this;
        }

        public Criteria andJobusernameIsNull() {
            addCriterion("JOBUSERNAME is null");
            return (Criteria) this;
        }

        public Criteria andJobusernameIsNotNull() {
            addCriterion("JOBUSERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobusernameEqualTo(String value) {
            addCriterion("JOBUSERNAME =", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameNotEqualTo(String value) {
            addCriterion("JOBUSERNAME <>", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameGreaterThan(String value) {
            addCriterion("JOBUSERNAME >", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameGreaterThanOrEqualTo(String value) {
            addCriterion("JOBUSERNAME >=", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameLessThan(String value) {
            addCriterion("JOBUSERNAME <", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameLessThanOrEqualTo(String value) {
            addCriterion("JOBUSERNAME <=", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameLike(String value) {
            addCriterion("JOBUSERNAME like", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameNotLike(String value) {
            addCriterion("JOBUSERNAME not like", value, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameIn(List<String> values) {
            addCriterion("JOBUSERNAME in", values, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameNotIn(List<String> values) {
            addCriterion("JOBUSERNAME not in", values, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameBetween(String value1, String value2) {
            addCriterion("JOBUSERNAME between", value1, value2, "jobusername");
            return (Criteria) this;
        }

        public Criteria andJobusernameNotBetween(String value1, String value2) {
            addCriterion("JOBUSERNAME not between", value1, value2, "jobusername");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 31 14:23:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STP_SCHEDULE_LOG
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}