package skyline.stp.repository.model;

import java.io.Serializable;

public class StpScheduleJob implements Serializable{
    /** 任务调度的参数key */
    public static final String JOB_PARAM_KEY    = "jobParam";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.PKID
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_NAME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_GROUP
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_TRIGGER
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobTrigger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_STATUS
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_ACTION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_METHOD
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.JOB_PARAM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String jobParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.SPRING_ID
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String springId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.CRON_EXPRESSION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.IS_SYNC
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String isSync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.DESCRIPTION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.CREATE_TIME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.DELETEDFLAG
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String deletedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.RECVERSION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private Long recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.SCHEDULE_TYPE
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private String scheduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.SUCESS_NUM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private Long sucessNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_JOB.FAIL_NUM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    private Long failNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.PKID
     *
     * @return the value of STP_SCHEDULE_JOB.PKID
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.PKID
     *
     * @param pkid the value for STP_SCHEDULE_JOB.PKID
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_NAME
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_NAME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_NAME
     *
     * @param jobName the value for STP_SCHEDULE_JOB.JOB_NAME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_GROUP
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_GROUP
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_GROUP
     *
     * @param jobGroup the value for STP_SCHEDULE_JOB.JOB_GROUP
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_TRIGGER
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_TRIGGER
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobTrigger() {
        return jobTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_TRIGGER
     *
     * @param jobTrigger the value for STP_SCHEDULE_JOB.JOB_TRIGGER
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobTrigger(String jobTrigger) {
        this.jobTrigger = jobTrigger == null ? null : jobTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_STATUS
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_STATUS
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_STATUS
     *
     * @param jobStatus the value for STP_SCHEDULE_JOB.JOB_STATUS
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus == null ? null : jobStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_ACTION
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_ACTION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobAction() {
        return jobAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_ACTION
     *
     * @param jobAction the value for STP_SCHEDULE_JOB.JOB_ACTION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobAction(String jobAction) {
        this.jobAction = jobAction == null ? null : jobAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_METHOD
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_METHOD
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobMethod() {
        return jobMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_METHOD
     *
     * @param jobMethod the value for STP_SCHEDULE_JOB.JOB_METHOD
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobMethod(String jobMethod) {
        this.jobMethod = jobMethod == null ? null : jobMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.JOB_PARAM
     *
     * @return the value of STP_SCHEDULE_JOB.JOB_PARAM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getJobParam() {
        return jobParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.JOB_PARAM
     *
     * @param jobParam the value for STP_SCHEDULE_JOB.JOB_PARAM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setJobParam(String jobParam) {
        this.jobParam = jobParam == null ? null : jobParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.SPRING_ID
     *
     * @return the value of STP_SCHEDULE_JOB.SPRING_ID
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getSpringId() {
        return springId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.SPRING_ID
     *
     * @param springId the value for STP_SCHEDULE_JOB.SPRING_ID
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setSpringId(String springId) {
        this.springId = springId == null ? null : springId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.CRON_EXPRESSION
     *
     * @return the value of STP_SCHEDULE_JOB.CRON_EXPRESSION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.CRON_EXPRESSION
     *
     * @param cronExpression the value for STP_SCHEDULE_JOB.CRON_EXPRESSION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.IS_SYNC
     *
     * @return the value of STP_SCHEDULE_JOB.IS_SYNC
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.IS_SYNC
     *
     * @param isSync the value for STP_SCHEDULE_JOB.IS_SYNC
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setIsSync(String isSync) {
        this.isSync = isSync == null ? null : isSync.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.DESCRIPTION
     *
     * @return the value of STP_SCHEDULE_JOB.DESCRIPTION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.DESCRIPTION
     *
     * @param description the value for STP_SCHEDULE_JOB.DESCRIPTION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.CREATE_TIME
     *
     * @return the value of STP_SCHEDULE_JOB.CREATE_TIME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.CREATE_TIME
     *
     * @param createTime the value for STP_SCHEDULE_JOB.CREATE_TIME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.UPDATE_TIME
     *
     * @return the value of STP_SCHEDULE_JOB.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.UPDATE_TIME
     *
     * @param updateTime the value for STP_SCHEDULE_JOB.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.DELETEDFLAG
     *
     * @return the value of STP_SCHEDULE_JOB.DELETEDFLAG
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.DELETEDFLAG
     *
     * @param deletedflag the value for STP_SCHEDULE_JOB.DELETEDFLAG
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setDeletedflag(String deletedflag) {
        this.deletedflag = deletedflag == null ? null : deletedflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.RECVERSION
     *
     * @return the value of STP_SCHEDULE_JOB.RECVERSION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public Long getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.RECVERSION
     *
     * @param recversion the value for STP_SCHEDULE_JOB.RECVERSION
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setRecversion(Long recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.SCHEDULE_TYPE
     *
     * @return the value of STP_SCHEDULE_JOB.SCHEDULE_TYPE
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public String getScheduleType() {
        return scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.SCHEDULE_TYPE
     *
     * @param scheduleType the value for STP_SCHEDULE_JOB.SCHEDULE_TYPE
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setScheduleType(String scheduleType) {
        this.scheduleType = scheduleType == null ? null : scheduleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.SUCESS_NUM
     *
     * @return the value of STP_SCHEDULE_JOB.SUCESS_NUM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public Long getSucessNum() {
        return sucessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.SUCESS_NUM
     *
     * @param sucessNum the value for STP_SCHEDULE_JOB.SUCESS_NUM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setSucessNum(Long sucessNum) {
        this.sucessNum = sucessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_JOB.FAIL_NUM
     *
     * @return the value of STP_SCHEDULE_JOB.FAIL_NUM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public Long getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_JOB.FAIL_NUM
     *
     * @param failNum the value for STP_SCHEDULE_JOB.FAIL_NUM
     *
     * @mbggenerated Thu Aug 27 14:58:22 CST 2015
     */
    public void setFailNum(Long failNum) {
        this.failNum = failNum;
    }
}