package skyline.stp.repository.model;

public class StpScheduleLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.PKID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.TABLENAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.TYPE
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.ROWPKID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String rowpkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBCODE
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBNAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBGROUP
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBDESC
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBTIME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBUSERID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.JOBUSERNAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String jobusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STP_SCHEDULE_LOG.REMARK
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.PKID
     *
     * @return the value of STP_SCHEDULE_LOG.PKID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.PKID
     *
     * @param pkid the value for STP_SCHEDULE_LOG.PKID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.TABLENAME
     *
     * @return the value of STP_SCHEDULE_LOG.TABLENAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.TABLENAME
     *
     * @param tablename the value for STP_SCHEDULE_LOG.TABLENAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.TYPE
     *
     * @return the value of STP_SCHEDULE_LOG.TYPE
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.TYPE
     *
     * @param type the value for STP_SCHEDULE_LOG.TYPE
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.ROWPKID
     *
     * @return the value of STP_SCHEDULE_LOG.ROWPKID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getRowpkid() {
        return rowpkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.ROWPKID
     *
     * @param rowpkid the value for STP_SCHEDULE_LOG.ROWPKID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setRowpkid(String rowpkid) {
        this.rowpkid = rowpkid == null ? null : rowpkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBCODE
     *
     * @return the value of STP_SCHEDULE_LOG.JOBCODE
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobcode() {
        return jobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBCODE
     *
     * @param jobcode the value for STP_SCHEDULE_LOG.JOBCODE
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobcode(String jobcode) {
        this.jobcode = jobcode == null ? null : jobcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBNAME
     *
     * @return the value of STP_SCHEDULE_LOG.JOBNAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobname() {
        return jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBNAME
     *
     * @param jobname the value for STP_SCHEDULE_LOG.JOBNAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobname(String jobname) {
        this.jobname = jobname == null ? null : jobname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBGROUP
     *
     * @return the value of STP_SCHEDULE_LOG.JOBGROUP
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobgroup() {
        return jobgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBGROUP
     *
     * @param jobgroup the value for STP_SCHEDULE_LOG.JOBGROUP
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobgroup(String jobgroup) {
        this.jobgroup = jobgroup == null ? null : jobgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBDESC
     *
     * @return the value of STP_SCHEDULE_LOG.JOBDESC
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobdesc() {
        return jobdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBDESC
     *
     * @param jobdesc the value for STP_SCHEDULE_LOG.JOBDESC
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobdesc(String jobdesc) {
        this.jobdesc = jobdesc == null ? null : jobdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBTIME
     *
     * @return the value of STP_SCHEDULE_LOG.JOBTIME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobtime() {
        return jobtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBTIME
     *
     * @param jobtime the value for STP_SCHEDULE_LOG.JOBTIME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobtime(String jobtime) {
        this.jobtime = jobtime == null ? null : jobtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBUSERID
     *
     * @return the value of STP_SCHEDULE_LOG.JOBUSERID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobuserid() {
        return jobuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBUSERID
     *
     * @param jobuserid the value for STP_SCHEDULE_LOG.JOBUSERID
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobuserid(String jobuserid) {
        this.jobuserid = jobuserid == null ? null : jobuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.JOBUSERNAME
     *
     * @return the value of STP_SCHEDULE_LOG.JOBUSERNAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getJobusername() {
        return jobusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.JOBUSERNAME
     *
     * @param jobusername the value for STP_SCHEDULE_LOG.JOBUSERNAME
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setJobusername(String jobusername) {
        this.jobusername = jobusername == null ? null : jobusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STP_SCHEDULE_LOG.REMARK
     *
     * @return the value of STP_SCHEDULE_LOG.REMARK
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STP_SCHEDULE_LOG.REMARK
     *
     * @param remark the value for STP_SCHEDULE_LOG.REMARK
     *
     * @mbggenerated Mon Aug 31 14:23:26 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}